version: 2

models:
  - name: metadata_indicateurs
    columns:
      - name: indic_id
        data_type: text
        description: "Identifiant de l'indicateur"
        meta:
            pilote_show: true
            pilote_alias: indic_id
            pilote_edit_isEditable: false
            pilote_edit_boxType: text
            pilote_disp_dispDesc: false
            pilote_create_mandatory: true
            pilote_create_defaultValue: null
      - name: indic_parent_indic
        data_type: text
        description: "Indicateur parent"
        meta:
            pilote_show: true
            pilote_alias: "Indicateur parent"
            pilote_edit_isEditable: true
            pilote_edit_regex: "IND-\\d\\d\\d"
            pilote_edit_regexViolationMessage: "Le code de l'indicateur parent doit être au format 'IND-XXX'"
            pilote_edit_boxType: text
            pilote_disp_dispDesc: false
            pilote_create_mandatory: false
            pilote_create_defaultValue: null
      - name: indic_parent_ch
        data_type: text
        description: "Code du chantier associé à cet indicateur, au format CH-XXX."
        meta:
            pilote_show: true
            pilote_alias: "Chantier associé"
            pilote_edit_isEditable: true
            pilote_edit_regex: "CH-\\d\\d\\d"
            pilote_edit_regexViolationMessage: "Le code du chantier parent doit être au format 'CH-XXX'"
            pilote_edit_boxType: text
            pilote_disp_dispDesc: true
            pilote_create_mandatory: true
            pilote_create_defaultValue: null
      - name: indic_nom
        data_type: text
        description: "Nom complet de l'indicateur"
        meta:
            pilote_show: true
            pilote_alias: "Nom"
            pilote_edit_isEditable: true
            pilote_edit_regex: ".*"
            pilote_edit_regexViolationMessage: null
            pilote_edit_boxType: text
            pilote_disp_dispDesc: false
            pilote_create_mandatory: true
            pilote_create_defaultValue: null
      - name: indic_nom_baro
        data_type: text
        description: "Nom de cet indicateur dans le baromètre des résultats de l'action publique."
        meta:
            pilote_show: true
            pilote_alias: "Nom baromètre"
            pilote_edit_boxType: text
            pilote_disp_dispDesc: true
            pilote_create_mandatory: false
            pilote_create_defaultValue: null"
      - name: indic_descr
        data_type: text
        description: "Description de l'indicateur"
        meta:
            pilote_show: true
            pilote_alias: "Description"
            pilote_edit_isEditable: true
            pilote_edit_regex: ".*"
            pilote_edit_regexViolationMessage: null
            pilote_edit_boxType: textarea
            pilote_disp_dispDesc: true
            pilote_create_mandatory: true
            pilote_create_defaultValue: null
      - name: indic_descr_baro
        data_type: text
        description: "Description de l'indicateur dans le baromètre de l'action publique"
        meta:
            pilote_show: true
            pilote_alias: "Description baromètre"
            pilote_edit_boxType: textarea
            pilote_disp_dispDesc: true
            pilote_create_mandatory: false
            pilote_create_defaultValue: null
      - name: indic_is_perseverant
        data_type: boolean
        description: "Indique si l'indicateur est perseverant"
        meta:
            pilote_show: true
            pilote_alias: "Persévérant"
            pilote_edit_isEditable: false
            pilote_create_mandatory: true
            pilote_create_defaultValue: false
      - name: indic_is_phare
        data_type: boolean
        description: "Indique si l'indicateur est phare"
        meta:
            pilote_show: true
            pilote_alias: "Phare"
            pilote_edit_isEditable: true
            pilote_create_mandatory: true
            pilote_create_defaultValue: false
      - name: indic_is_baro
        description: "Indicateur présent dans le baromètre des résultats de l'action publique"
        data_type: boolean
        meta:
            pilote_show: true
            pilote_alias: "Baromètre"
            pilote_edit_isEditable: false
            pilote_create_mandatory: true
            pilote_create_defaultValue: false
      - name: indic_type
        data_type: text
        description: |
            Typologie de l'indicateur.

            Il peut s'agir d'indicaeur d'impact (`IMPACT`), de déploiement (`DEPL`), de contexte (`CONTEXTE`), de qualité de service (`Q_SERV`) ou de rebond (`REBOND`).
        meta:
            pilote_show: true
            pilote_alias: "Typologie"
            pilote_edit_isEditable: true
            pilote_edit_acceptedValuesViolationMessage: "Veuillez choisir une typologie d'indicateur valide parmi: "   
            pilote_edit_acceptedValues: >
              [{"order_id": 1, "value": "IMPACT", "name": "Impact", "desc": "Indicateur d'impact"}, {"order_id": 2, "value": "DEPL", "name": "Déploiement", "desc": "Indicateur de déploiement"}, {"order_id": 3, "value": "CONTEXTE", "name": "De contexte", "desc": "Indicateur de contexte"}, {"order_id": 4, "value": "Q_SERV", "name": "De qualité de service", "desc": "Mesure la qualité du service rendu."}, {"order_id": 5, "value": "REBOND", "name": "Effets rebonds", "desc": "Effets rebonds engendrés par la mise en place du chantier"}]   
            pilote_disp_dispDesc: true
            pilote_create_mandatory: true
            pilote_create_defaultValue: "IMPACT"
      - name: indic_source
        description: "Source déclarée des données de l'indicateur"
        data_type: text
        meta:
            pilote_show: true
            pilote_alias: "Source"
            pilote_edit_isEditable: false
            pilote_edit_boxType: text
            pilote_disp_dispDesc: true
            pilote_create_mandatory: false
            pilote_create_defaultValue: "Pas de source renseignée"
      - name: indic_source_url
        data_type: text
        description: "URL de la source de donnée déclarée (si accessible publiquement)"
        meta:
            pilote_show: true
            pilote_alias: "Source (URL)"
            pilote_edit_isEditable: false
            pilote_edit_boxType: text
            pilote_create_mandatory: false
            pilote_create_defaultValue: null
      - name: indic_methode_calcul
        data_type: text
        description: "Méthode de calcul pour l'obtention des données."
        meta:
            pilote_show: true
            pilote_alias: "Méthode de calcul"
            pilote_edit_isEditable: false
            pilote_edit_boxType: textarea
            pilote_disp_dispDesc: true
            pilote_create_mandatory: false
            pilote_create_defaultValue: null
      - name: indic_unite
        data_type: text
        description: "Unité de l'indicateur"
        meta:
            pilote_show: true
            pilote_alias: "Unité"
            pilote_edit_isEditable: true
            pilote_edit_regex: ".*"
            pilote_edit_regexViolationMessage: null
            pilote_edit_boxType: text
            pilote_create_mandatory: true
            pilote_create_defaultValue: null
      - name: indic_hidden_pilote
        data_type: boolean
        description: "Indique si l'indicateur est affiché dans Pilote. **Ne fonctionne pas**"
        meta:
            pilote_show: true
            pilote_alias: "Masqué"
            pilote_disp_dispDesc: true
            pilote_create_mandatory: true
            pilote_create_defaultValue: false
      - name: indic_schema
        data_type: text
        description: "Nom du schema associé. Cela permet la restriction de la saisie de données."
        meta:
            pilote_show: true
            pilote_alias: "Contraintes"
            pilote_edit_isEditable: false
            pilote_edit_boxType: text
            pilote_edit_acceptedValuesViolationMessage: "Veuillez choisir des contraintes de saisie parmi: "      
            pilote_edit_acceptedValues: >
              [{"order_id": 1, "value": "sans-contraintes.json", "name": "-", "desc": "Pas de contraintes particulières"}, {"order_id": 2, "value": "restrict-dept.json", "name": "Saisie départementale", "desc": "Saisie restreinte au niveau départemental"}, {"order_id": 3, "value": "restrict-0-100.json", "name": "Dans [0,100]", "desc": "Saisie entre 0 et 100."}]
            pilote_create_mandatory: true
            pilote_create_defaultValue: "sans-contraintes.json"
      - name: zg_applicable
        data_type: text
        description: "*Zone-group* applicable à cet indicateur. Voir `metadata_zonegroup`"
        meta:
            pilote_show: true
            pilote_alias: "ZG"
            pilote_edit_isEditable: true
            pilote_edit_regex: "ZG-\\d\\d\\d"
            pilote_edit_regexViolationMessage: "Le code de la ZG doit être au format 'ZG-XXX'"
            pilote_edit_boxType: text
            pilote_disp_dispDesc: true
            pilote_create_mandatory: false
            pilote_create_defaultValue: null
