version: 2

models:
  - name: int_chantiers_with_mailles_and_territoires
    description: "Vue intermédiaire afin de décliner les chantiers pour tous leurs territoires (maille + code insee)"
  - name: int_dfakto_indicateurs_metrics
    description: "Vue intermédiaire pour récupérer les métriques (type TA) des indicateurs en provenance de dfakto"
  - name: projet_structurant_temporaire
    description: "Vue intermédiaire afin de créer une table projet_structurant avec un id unique qui sera réutilisée pour toutes les tables en ayant besoin (de l'id unique)"
