version: 2

models:
  - name: int_chantiers_with_mailles_and_territoires
    description: "Vue intermédiaire afin de décliner les chantiers pour tous leurs territoires (maille + code insee)"
  - name: int_indicateurs_zones_applicables
    description: "Une ligne pour chaque indicateur X chaque territoire. Uniquement les indicateurs applicables sur une zone groupe. Indique si l'indicateur est applicable sur le territoire"
    columns:
      - name: indic_id
        description: "ID de l'indicateur"
      - name: chantier_id
        description: "ID du chantier"
      - name: zone_id
        description: "ID du territoire"
      - name: est_applicable
        description: "Si le chantier est applicable sur le territoire"
  - name: int_ponderation_reelle
    description: |
      Cette table indique 3 pondérations pour chaque couple {indicateur, zone}:

      - `poids_zone_declaree`: pondération déclarée (recueillie par le formulaire DS)
      - `poids_zone_appl`: si l'indicateur est applicable sur cette zone, c'est la pondération déclarée sinon 0 
      - `poids_zone_reel`: pondération réelle, recalculée sur **base 100**. En effet, on normalise la pondération pour que la somme de toutes les pondérations des indicateurs applicables se somment à la valeur **100**.

    columns:
      - name: indic_id
        description: Identifiant unique de l'indicateur
      - name: zone_id
        description: Identifiant de la zone
      - name: est_applicable
        data_type: boolean
        description: Indique si l'indicateur est applicable sur cette zone
      - name: poids_zone_declaree
        description: Pondération déclarée (dans le DS)
      - name: poids_zone_appl
        description: Pondération en prenant en compte les *zones applicables*
      - name: poids_zone_reel
        description: "Pondération réelle: en prenant en compte les *zones applicables* + la remise sur **base 100**"
        
  - name: last_update_indic_zone
    description: |
      Pour chaque couple {indicateur-zone}, on indique le **rapport** et la **date** de ce rapport qui modifie cet indicateur sur cette zone.

      Etant donné que l'on part de la table `raw_data.mesure_indicateur`, si une valeur qui est renvoyée à la webapp est issue d'une aggrégation, il n'existe **pas d'import correspondant** donc **aucune ligne** ne sera renvoyée pour ce couple {indicateur-zone}.
    columns:
      - name: indic_id
        description: "Identifiant de l'indicateur"
      - name: zone_id
        description: "Identifiant de la zone"
      - name: territoire_code
        description: "Code du territoire. Utilisé par le front, équivalent à `zone_id`"
      - name: dernier_import_rapport_id
        description: "UUID du dernier rapport pour cet {indicateur-zone}"
      - name: dernier_import_date
        description: "Date du dernier rapport (`dernier_import_rapport_id`)"
      - name: dernier_import_auteur
        description: "Auteur du dernier rapport qui modifie cet indicateur sur cette zone"
  - name: last_update_indic
    description: |
      Pour chaque {indicateur}, on indique le **rapport** et la **date** de ce rapport qui modifie cet indicateur sur **n'importe quelle zone**.

      Cela permet par exemple d'avoir une date à afficher pour une **valeur issue d'une aggrégation**. En effet, dans ce cas, une valeur aggrégée issue de calculs peut être renvoyée vers le front mais n'est présente dans aucun rapport. 
    columns:
      - name: indic_id
        description: "Identifiant de l'indicateur"
      - name: dernier_import_rapport_id_indic
        description: "UUID du dernier rapport pour cet {indicateur} (sur n'importe quelle zone)"
      - name: dernier_import_date_indic
        description: "Date du dernier rapport (`dernier_import_rapport_id_indic`)"
      - name: dernier_import_auteur_indic
        description: "Auteur du dernier rapport pour cet {indicateur} (sur n'importe quelle zone)"
  - name: int_directeurs_projets
    description: "Une ligne pour chaque chantier qui indique son/ses DP (Directeur de Projet)."
    columns:
      - name: nom
        description: "Liste des noms des DP"
      - name: email
        description: "Liste des emails des DP"
      - name: chantier_id
        description: "Chantier concerné"
  - name: int_referents_territoriaux
    description: "Une ligne pour chaque zone qui indique son/ses référents territoriaux (ou référents Pilote)"
    columns:
      - name: nom
        description: "Liste des noms des référents"
      - name: email
        description: "Liste des emails des référents"
      - name: territoire_code
        description: "Code du territoire concerné"
      - name: zone_id
        description: "ID de la zone concernée"
  - name: int_responsables_locaux
    description: "Une ligne pour chaque zone et chaque chantier qui indique son/ses responsables locaux"
    columns:
      - name: nom
        description: "Liste des noms des responsables"
      - name: email
        description: "Liste des emails des responsables"
      - name: chantier_id
        description: "Chantier concerné"
      - name: territoire_code
        description: "Code du territoire concerné"
      - name: zone_id
        description: "ID de la zone concernée"
  - name: int_chantiers_zone_applicables
    description: "Une ligne pour chaque chantier et chaque territoire pour les chantiers uniquement applicable sur une zone groupe. Indique si le chantier est applicable sur le territoire"
    columns:
      - name: chantier_id
        description: "ID du chantier"
      - name: zone_id
        description: "ID du territoire"
      - name: zone_est_applicable
        description: "Si le chantier est applicable sur le territoire"
      - name: maille
        description: "Maille du territoire"
      - name: zone_id
        description: "ID de la zone concernée"
