version: '3.8'
services:
  app:
    image: node:lts-alpine
    depends_on:
      - postgresql
    restart: always
    environment:
      DATABASE_URL: postgresql://postgresql:secret@postgresql:5432/postgresql
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    command: sh -c "cd /app && npm install && npm run dev"
    tty: true
  postgresql:
    image: scalingo/postgresql:13.8.0-2
    environment:
      DB_USER: postgresql
      DB_PASSWORD: secret
      DB_ADMIN_PASSWORD: admin-secret
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql
    command: /postgresql
    tty: true
