services:
  postgres:
    hostname: postgres
    container_name: pilote_postgres
    depends_on:
      - pilote_traefik
    image: postgres:16.2-alpine
    shm_size: 1g
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes: 
      - db_dbt_pilote:/var/lib/postgresql/data

  postgres_test:
    hostname: postgres_test
    container_name: pilote_postgres_test
    depends_on:
      - pilote_traefik
    image: postgres:16.2-alpine
    shm_size: 1g
    ports:
      - "${POSTGRES_TEST_PORT:-5433}:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}

  pilote_traefik:
    container_name: pilote_traefik
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "${TRAEFIK_PORT:-80}:80"
      #- "${TRAEFIK_API_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_dbt_pilote:
    driver: local

# Usage :
# - (optionnel) "docker compose build" pour construire les images
# - "docker compose up" pour lancer la db, la doc, et la webapp
# - (optionnel) "docker compose run pilote_scripts" pour entrer dans le container et lancer les scripts dbt via "/bin/bash scripts/<name-of-the-script>.sh"
# - (optionnel) OU "docker compose run pilote_scripts scripts/<name-of-the-script>.sh" pour lancer le script dbt <name-of-the-script>.sh
# - (optionnel) "docker container exec -it pilote_webapp /bin/sh" pour entrer dans le container webapp et éventuellement entrer des commandes (ex: npm, yarn, ...)
