import { FunctionComponent } from "react";
import Bloc from "@/components/_commons/Bloc/Bloc";
import Titre from "@/components/_commons/Titre/Titre";
import { wording } from "@/client/utils/i18n/i18n";
import "@gouvfr/dsfr/dist/component/download/download.min.css";
import {
  Tableau,
  TableauCellule,
  TableauCelluleEnTete,
  TableauCorps,
  TableauEnTete,
  TableauLigne,
} from "@/components/shared/Tableau";

const PageImportIndicateurSectionRessource: FunctionComponent = () => {
  return (
    <section className="bg-dsfr-alt-blue-france">
      <div className="fr-container fr-py-3w">
        <Titre baliseHtml="h2" className="text-primary">
          {wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.TITRE}
        </Titre>
        <Bloc>
          <Titre baliseHtml="h3">
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_EXPLICATION_IMPORT.TITRE
            }
          </Titre>
          <p>
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_EXPLICATION_IMPORT.SOUS_TITRE
            }
          </p>
          <ul>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.IDENTIFIANT_INDIC
                    .CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.IDENTIFIANT_INDIC.EXPLICATION}`}
              </span>
            </li>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.ZONE_ID.CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.ZONE_ID.EXPLICATION}`}
              </span>
            </li>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.ZONE_NOM.CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.ZONE_NOM.EXPLICATION}`}
              </span>
            </li>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.DATE_VALEUR.CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.DATE_VALEUR.EXPLICATION}`}
              </span>
            </li>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.TYPE_VALEUR.CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.TYPE_VALEUR.EXPLICATION}`}
              </span>
            </li>
            <li>
              <b>
                {
                  wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                    .SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.VALEUR.CHAMP
                }
              </b>
              <span>
                {` • ${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_EXPLICATION_IMPORT.LISTE_CHAMPS.VALEUR.EXPLICATION}`}
              </span>
            </li>
          </ul>
          <p>
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_EXPLICATION_IMPORT.FORMAT_ACCEPTE
            }
          </p>
          <Tableau className="mb-10">
            <TableauEnTete>
              <tr>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE
                      .IDENTIFIANT_INDIC
                  }
                </TableauCelluleEnTete>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE.ZONE_ID
                  }
                </TableauCelluleEnTete>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE.ZONE_NOM
                  }
                </TableauCelluleEnTete>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE
                      .DATE_VALEUR
                  }
                </TableauCelluleEnTete>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE
                      .TYPE_VALEUR
                  }
                </TableauCelluleEnTete>
                <TableauCelluleEnTete>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.ENTETE.VALEUR
                  }
                </TableauCelluleEnTete>
              </tr>
            </TableauEnTete>
            <TableauCorps>
              <TableauLigne>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .IDENTIFIANT_INDIC
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .ZONE_ID
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .ZONE_NOM
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .DATE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .TYPE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_1
                      .VALEUR
                  }
                </TableauCellule>
              </TableauLigne>
              <TableauLigne>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .IDENTIFIANT_INDIC
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .ZONE_ID
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .ZONE_NOM
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .DATE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .TYPE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_2
                      .VALEUR
                  }
                </TableauCellule>
              </TableauLigne>
              <TableauLigne>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .IDENTIFIANT_INDIC
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .ZONE_ID
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .ZONE_NOM
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .DATE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .TYPE_VALEUR
                  }
                </TableauCellule>
                <TableauCellule>
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_EXPLICATION_IMPORT.TABLEAU_CHAMPS.LIGNE_EXEMPLE_3
                      .VALEUR
                  }
                </TableauCellule>
              </TableauLigne>
            </TableauCorps>
          </Tableau>
          <Titre baliseHtml="h3">
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_REFERENTIEL.TITRE
            }
          </Titre>
          <p>
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_REFERENTIEL.SOUS_TITRE
            }
          </p>
          <div className="flex">
            <div className="fr-download fr-mr-3w fr-hidden">
              <p>
                <a
                  className="fr-download__link"
                  download
                  href="/referentiel/referentiel_territoires.xlsx"
                >
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_REFERENTIEL
                      .LABEL_BOUTON_TELECHARGER_REFERENTIEL_INDICATEUR
                  }
                  <span className="fr-download__detail">
                    {
                      wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                        .SECTION_REFERENTIEL
                        .FORMAT_BOUTON_TELECHARGER_REFERENTIEL_INDICATEUR
                    }
                  </span>
                </a>
              </p>
            </div>
            <div className="fr-download">
              <p>
                <a
                  className="fr-download__link"
                  download
                  href="/referentiel/referentiel_territoires.xlsx"
                >
                  {
                    wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                      .SECTION_REFERENTIEL
                      .LABEL_BOUTON_TELECHARGER_REFERENTIEL_TERRITOIRE
                  }
                  <span className="fr-download__detail">
                    {
                      wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                        .SECTION_REFERENTIEL
                        .FORMAT_BOUTON_TELECHARGER_REFERENTIEL_TERRITOIRE
                    }
                  </span>
                </a>
              </p>
            </div>
          </div>
          <Titre baliseHtml="h3">
            {
              wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                .SECTION_EXPLICATION_FICHIER.TITRE
            }
          </Titre>
          <ul>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_1
              }
            </li>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_2
              }
            </li>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_3
              }
            </li>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_4
              }
            </li>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_5
              }
            </li>
            <li>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_EXPLICATION_FICHIER.EXPLICATION_FICHIER_6
              }
            </li>
          </ul>
          <p>
            <b>
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_CONTACT.MESSAGE_CONTACT
              }
            </b>
            <a
              className="fr-link"
              href={`mailto:${wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE.SECTION_CONTACT.ADRESSE_MAIL}`}
            >
              {
                wording.PAGE_IMPORT_MESURE_INDICATEUR.SECTION_RESSOURCE
                  .SECTION_CONTACT.ADRESSE_MAIL
              }
            </a>
          </p>
        </Bloc>
      </div>
    </section>
  );
};

export default PageImportIndicateurSectionRessource;
