export type DonneeChantier = {
  id: string;
  nom: string;
  maille: string;
  axe: string;
  territoireCode: string;
  ministèreNom: string | null;
  tauxDAvancementAnnuel: number;
  tauxDAvancementNational: number;
  tauxDAvancementRégional: number;
  tauxDAvancementDépartemental: number;
  météo: string;
  directeursProjet: string[];
  directeursProjetMails: string[];
  responsablesLocaux: string[] | null;
  responsablesLocauxMails: string[] | null;
  statut: string;
  estBaromètre: boolean;
  estTerritorialisé: boolean;
  commActionsÀVenir: string;
  commActionsÀValoriser: string;
  commFreinsÀLever: string;
  commCommentairesSurLesDonnées: string;
  commAutresRésultats: string;
  commAutresRésultatsNonCorrélésAuxIndicateurs: string;
  decStratSuiviDesDécisions: string;
  objNotreAmbition: string;
  objDéjàFait: string;
  objÀFaire: string;
  synthèseDesRésultats: string;
};
