export type DonneeChantier = {
  id: string;
  nom: string;
  maille: string;
  axe: string;
  territoireCode: string;
  ministèreNom: string | null;
  tauxDAvancementNational: number | null;
  tauxDAvancementRégional: number | null;
  tauxDAvancementDépartemental: number | null;
  météo: string;
  directeursProjet: string[] | null;
  directeursProjetMails: string[] | null;
  responsablesLocaux: string[] | null;
  responsablesLocauxMails: string[] | null;
  statut: string;
  estBaromètre: boolean;
  estTerritorialisé: boolean;
  commActionsÀVenir: string | null;
  commActionsÀValoriser: string | null;
  commFreinsÀLever: string | null;
  commCommentairesSurLesDonnées: string | null;
  commAutresRésultats: string | null;
  commAutresRésultatsNonCorrélésAuxIndicateurs: string | null;
  decStratSuiviDesDécisions: string | null;
  objNotreAmbition: string | null;
  objDéjàFait: string | null;
  objÀFaire: string | null;
  synthèseDesRésultats: string | null;
};
