version: 2

macros:
  - name: df3_date_early
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Compare si une date est **antérieure** à ce qui est attendu.
    arguments:
      - name: colname_date
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant une date à vérifier.
  - name: df3_date_late
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Compare si une date est **postérieure** à ce qui est attendu.
    arguments:
      - name: colname_date
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant une date à vérifier.
  - name: df3_not_equal_bool
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Compare si deux booléens sont **non null et identiques**.
    arguments:
      - name: colname
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant un booléen à comparer.
  - name: df3_not_equal
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Compare si deux valeurs numériques sont égales. Le paramètre `tolerance` permet d'indiquer une fenêtre de précision.
    arguments:
      - name: colname
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant un nombre à comparer.
      - name: tolerance
        type: float
        description: Nombre dans `[0,1]` qui indique le seuil de pourcentage de différence des deux nombres au dessus duquel on considère que les deux nombres sont **différents**. Par exemple, `0.01` signifie que deux nombres seront considérés non égaux s'ils varient de `1%` ou plus.
  - name: df3_should_notnull
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Indique lorsqu'une valeur vaut `NULL`, mais ne **devrait pas**.
    arguments:
      - name: colname
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant une valeur à vérifier.
  - name: df3_should_null
    description: |
      Macro de test de la `df2.df3_indicateur` par rapport à `public.indicateur`. 
      
      Indique lorsqu'une valeur **n'est pas** `NULL`, mais **devrait l'être**.
    arguments:
      - name: colname
        type: string
        description: Nom de la colonne de `df2.df3_indicateur` et `public.indicateur` contenant une valeur à vérifier.
