version: 2

models:
  - name: mesure_select_last
    description: |
        Pour chaque {indic_id, metric_type, metric_date, zone_id}, on retourne la valeur la plus récente. Règles:

        - Si 2 valeurs pour le meme {indic_id, metric_type, metric_date, zone_id}, on retourne celle avec la date d'import la plus récente
        - Si 2 valeurs dans le même mois, à des jours différents, on garde **les deux**
        - Transformation de `'null'` et `''` vers un `NULL`
        