export const moduleNames = [
  "framework",
  "authentification",
  "chantiers",
  "parametrageIndicateur",
  "importIndicateur",
  "commentaires",
  "decisionStrategique",
  "objectif",
  "importSyntheseDesResultats",
  "importPublicationCSV",
  "gestionUtilisateur",
  "ficheConducteur",
  "parametrageNouveautes",
  "indicateurTerritoireValeurEvenement",
  "piloteEval",
  "habilitationsCoordinateur",
  "profilUtilisateur",
  "rapportsHebdomadaires",
  "albert",
  "parametrageCentreAide",
  "datajobsExecution",
  "gestionContenu",
  "ficheTerritoriale",
  "applicationLog",
  "actualites",
  "mbSync",
  "parametrageChantier",
  "referentiels",
  "annuaire",
] as const;

export type ModuleName = (typeof moduleNames)[number];
