export const moduleNames = [
  "shared",
  "authentification",
  "chantiers",
  "parametrageIndicateur",
  "importIndicateur",
  "commentaires",
  "decisionStrategique",
  "objectif",
  "importSyntheseDesResultats",
  "gestionUtilisateur",
  "ficheConducteur",
  "parametrageNouveautes",
  "indicateurTerritoireValeurEvenement",
  "piloteEval",
  "habilitationsCoordinateur",
  "profilUtilisateur",
  "rapportsHebdomadaires",
  "albert",
  "parametrageCentreAide",
  "datajobsExecution",
  "legacy",
  "applicationLog",
  "actualites",
  "mbSync",
  "metadataChantier",
  "metadataPorteur",
  "metadataPerimetre",
  "metadataZonegroup",
  "metadataAxe",
  "metadataPpg",
  "metadataEngagement",
] as const;

export type ModuleName = (typeof moduleNames)[number];
