version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.10.5
    ports:
      - "${PUBLISH_PORT}:8080"
    env_file: 
        - .env
    volumes:
      - ./pilote-api.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml