openapi: 3.1.0
x-stoplight:
  id: x0ygm9j5iky4x
info:
  title: pilote-api
  version: '1.0'
  summary: Cette API permet d'interagir avec Pilote.
  description: 'Via cette API, il est possible de récupérer les données de Pilote et d''importer des données dans la limite des autorisations fixées par votre compte.'
  contact:
    name: Colin DUGEAI
    email: colin.dugeaiATmodernisation.gouv.fr
servers:
  - url: 'http://localhost:3000'
    description: Local
  - url: 'http://172.17.0.1:3000'
    description: Docker local
paths:
  '/chantier/{chantier_id}':
    parameters:
      - schema:
          type: string
        name: chantier_id
        in: path
        required: true
    get:
      summary: Informations chantier
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chantier'
              examples:
                Example 1:
                  value:
                    id: CH-001
                    description: Description textuelle du premier chantier
                    nom: Premier chantier prioritaire
                    directeur_projet: Jean Dupont
                    ppg_id: PPG-123
                    porteurs: MEFSIN | MSAPH
                    perimetre_id: PER-019
                    territorialise: true
                    engagement: EMPLOI
                    etat: PUBLIE
      operationId: get-chantier-id
      description: Obtenir les informations sur un chantier
      parameters: []
    post:
      summary: Modifier un chantier
      operationId: post-chantier-id
      responses:
        '200':
          description: OK
      description: Obtenir les informations sur un chantier
components:
  schemas:
    Chantier:
      title: Chantier
      x-stoplight:
        id: p5jtbeh5h8v1h
      type: object
      description: Description complète d'un chantier prioritaire.
      examples:
        - id: CH-001
          description: Description textuelle du premier chantier
          nom: Premier chantier prioritaire
          directeur_projet: Jean Dupont
          ppg_id: PPG-123
          porteurs: MEFSIN | MSAPH
          perimetre_id: PER-019
          territorialise: true
          engagement: EMPLOI
          etat: PUBLIE
      properties:
        id:
          type: string
          description: Identifiant du chantier
          pattern: '^CH-[0-9][0-9][0-9]$'
        description:
          type: string
          x-stoplight:
            id: zdi3an2y785p5
          description: Description du chantier
        nom:
          type: string
          x-stoplight:
            id: cyz7ea8cxcy1a
          description: Nom du chantier
        directeur_projet:
          type: string
          x-stoplight:
            id: r49po0dyvgn0n
          description: Nom du directeur de projet
        ppg_id:
          x-stoplight:
            id: ztoyprmidlw0v
          description: Identifiant de la PPG
          type: string
          pattern: '^PPG-[0-9][0-9][0-9]$'
          example: PPG-001
        porteurs:
          type: string
          x-stoplight:
            id: zyifvj48w8g4s
          description: Liste des porteurs du chantier (séparés par " | ").
          example: MEFSIN | MSAPH
        perimetre_id:
          type: string
          x-stoplight:
            id: q2f4thq23mxe4
          example: PER-019
          pattern: '^PER-[0-9][0-9][0-9]$'
          description: Identifiant du périmètre du chantier
        territorialise:
          type: boolean
          x-stoplight:
            id: osknraxgj0nzn
          description: Etat de territorialisation du chantier (Oui/non)
        engagement:
          type: string
          x-stoplight:
            id: tx1xg9r1jx1e3
          enum:
            - EMPLOI
            - PROGRES
            - TE
            - ENGAG
          example: EMPLOI
          description: Engagement auquel appartient le chantier
        etat:
          type: string
          x-stoplight:
            id: r5xhoq4owsiaw
          enum:
            - PUBLIE
            - BROUILLON
            - NON_PUBLIE
          example: PUBLIE
          description: Etat de publication du chantier
      required:
        - id
        - description
        - nom
        - ppg_id
        - perimetre_id
        - territorialise
        - etat
      x-tags:
        - Chantier
    PPG:
      title: PPG
      x-stoplight:
        id: y5p9457oy9ahb
      type: object
      examples:
        - id: PPG-014
          nom: Première PPG
          description: Description de la PPG
          axe_id:
            id: EMPLOI
      properties:
        id:
          type: string
          description: Identifiant de la PPG
          pattern: '^PPG-[0-9][0-9][0-9]$'
          example: PPG-014
        nom:
          type: string
          x-stoplight:
            id: 38z6p01nyhsyz
          example: Mieux vivre de son travail
        description:
          type: string
          x-stoplight:
            id: q86g1ouyl59k9
        axe_id:
          $ref: '#/components/schemas/Axe'
          x-stoplight:
            id: 4tdqltir7n7y4
      required:
        - id
        - nom
    Axe:
      title: Axe
      x-stoplight:
        id: pkmunivqndbww
      type: object
      properties:
        id:
          type: string
          example: EMPLOI
  securitySchemes:
    abc-123:
      name: X-API-KEY
      type: apiKey
      in: header
      description: Cette clé d'API vous permet de vous authentifier et d'aacéder uniquement aux resources autorisées.
  parameters:
    chantier_id:
      name: chantier_id
      in: query
      schema:
        type: string
        pattern: bla
      description: Identifiant de chantier
      required: true
x-internal: false
