version: "3.8"

services:

  init-container:
    depends_on:
      - pg_pilote_review
    env_file:
      - ../.env.review
    build: 
      dockerfile: data_management/custom_build_image/Dockerfile
      context: ../..
    ports: [ "3000:3000" ]

  pg_pilote_review:
    image: postgres:14.1-alpine
    ports:
      - "5456:5432"
    env_file:
      - ../.env.review
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=postgres
  
