version: "3.8"

services:

  init-container:
    env_file:
      - ../.env.review
    build: 
      dockerfile: data_management/custom_build_image/Dockerfile
      context: .
    ports: [ "3000:3000" ]
