[project]
name = "datafactory-pilote-ppg"
version = "0.1.0"
description = "Datafactory de l'outil PILOTE"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chardet~=5.2.0",
    "dbt-core~=1.11.0",
    "dbt-duckdb~=1.11.0",
    "dbt-postgres~=1.11.0",
    "markdown2~=2.5",
    "python-dotenv~=1.0",
    "requests~=2.32",
    "elementary-data[postgres]~=0.23",
    "sqlfluff~=4.2.0",
    "sqlfluff-templater-dbt~=4.2.0",
    "pygithub~=2.4.0",
    "jinja2~=3.1.4",
    "sqlalchemy~=2.0.36",
    "pyyaml~=6.0",
    "pandas~=2.2",
    "uv>=0.11.8",
]


[dependency-groups]
dev = []

[tool.uv]
package = false
default-groups = "all"
exclude-newer = "1 week"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
