version: 2

models:
  - name: get_date_bascule_depassee
    description: >
      Indique si la date de bascule du TA annuel est dépassée ou non.

      En effet, cette date est paramétrée dans `dbt_project.yml` et vaut {{ var("dateBasculeTauxAnnuelAnneeCouranteString") }}:
      - avant cette date, le TA annuel affiché est celui de l'année dernière
      - après cette date, le TA annuel affiché est celui de l'année courante
    columns:
      - name: date_bascule
        description: "Date de bascule pour toutes les années (année ignorée)"
      - name: date_aujourdhui
        description: "Date du jour"
      - name: date_bascule_annee_courante
        description: "Date de bascule pour l'année en cours"
      - name: date_depassee
        description: "Booleen qui indique si la date de bascule est dépassée."
 