import { Chantier } from './FakeChantiers.interface';

/* eslint-disable sonarjs/no-duplicate-string */
export const chantiers: Chantier[] = [
  {
    id: 1,
    nom: "Assurer la couverture numérique du territoire par la fibre d'ici 2025",
    axe: 'RENFORCER NOTRE SOUVERNAINETÉ FRANÇAISE ET EUROPÉENNE',
    ppg: 'Devenir la première puissance numérique européenne',
    ministere: 'MEFSIN',
    nomAncienneReformePrioritaire: "Assurer une bonne couverture en internet fixe et en téléphonie mobile pour tous les Français d'ici 2022",
    trigramme: 'THD',
    precedentMinistereResponsable: 'Ministère de la Cohésion des territoires et des Relations avec les collectivités territoriales',
    meteo: 3,
    avancement: 0.55,
  },
  {
    id: 2,
    nom: "Favoriser l'inclusion numérique pour tous par la formation et les conseillers de proximité",
    axe: 'RENFORCER NOTRE SOUVERNAINETÉ FRANÇAISE ET EUROPÉENNE',
    ppg: 'Devenir la première puissance numérique européenne',
    ministere: 'MEFSIN',
    nomAncienneReformePrioritaire: 'Accompagnement au numérique pour tous, partout sur le territoire',
    trigramme: 'DAN',
    precedentMinistereResponsable: "Ministère de l'Economie des Finances et de la Relance",
    meteo: null,
    avancement: 0.99,
  },
  {
    id: 3,
    nom: 'Réussir la transition écologique des exploitations agricoles ',
    axe: 'RENFORCER NOTRE SOUVERNAINETÉ FRANÇAISE ET EUROPÉENNE',
    ppg: 'Assurer la souveraineté alimentaire et forestière en réusissant la transition écologique',
    ministere: 'MASA',
    nomAncienneReformePrioritaire: "Réduire l'utilisation des produits phytosanitaires et accélérer la transition écologique",
    trigramme: 'RUP',
    precedentMinistereResponsable: "Ministère de l'Agriculture et de l'Alimentation",
    meteo: 3,
    avancement: null,
  },
  {
    id: 4,
    nom: "Renouveler et former une génération d'agriculteurs et d'agricultrices ",
    axe: 'RENFORCER NOTRE SOUVERNAINETÉ FRANÇAISE ET EUROPÉENNE',
    ppg: "Renouveler et former une génération d'agriculteurs et d'agricultrices ",
    ministere: 'MASA',
    nomAncienneReformePrioritaire: 'Favoriser les nouvelles installations d’agriculteurs pour assurer le renouvellement des générations',
    trigramme: 'NIA',
    precedentMinistereResponsable: "Ministère de l'Agriculture et de l'Alimentation",
    meteo: 2,
    avancement: 1,
  },
  {
    id: 5,
    nom: 'Poursuivre le développement du CEJ',
    axe: 'ALLER VERS UNE SOCIETE DU PLEIN EMPLOI',
    ppg: "Améliorer le taux d'emploi des jeunes et des seniors",
    ministere: 'MTPEI',
    nomAncienneReformePrioritaire: '#1jeune1solution',
    trigramme: 'NTS',
    precedentMinistereResponsable: "Ministère du Travail de l'Emploi et de l'Insertion",
    meteo: 2,
    avancement: 0.48,
  },
  {
    id: 6,
    nom: "Poursuivre le développement de l'apprentissage",
    axe: 'ALLER VERS UNE SOCIETE DU PLEIN EMPLOI',
    ppg: "Mieux répondre aux besoins de compétences et préparer aux métiers d'avenir",
    ministere: 'MTPEI',
    nomAncienneReformePrioritaire: "Développer l'apprentissage",
    trigramme: 'APP',
    precedentMinistereResponsable: "Ministère du Travail de l'Emploi et de l'Insertion",
    meteo: 2,
    avancement: 0.87,
  },
  {
    id: 7,
    nom: "Former aux métiers d'avenir",
    axe: 'ALLER VERS UNE SOCIETE DU PLEIN EMPLOI',
    ppg: "Mieux répondre aux besoins de compétences et préparer aux métiers d'avenir",
    ministere: 'MTPEI',
    nomAncienneReformePrioritaire: "Préserver l'emploi et accompagner les entreprises par la formation",
    trigramme: 'AEF',
    precedentMinistereResponsable: "Ministère du Travail de l'Emploi et de l'Insertion",
    meteo: 2,
    avancement: 0.28,
  },
  {
    id: 8,
    nom: ' Amplifier le Plan vélo',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Devenir la première grande économie décarbonée avec des transports propres',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Déployer le plan vélo',
    trigramme: 'PVL',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 3,
    avancement: 0.67,
  },
  {
    id: 9,
    nom: 'Développer la part des voitures électriques',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Devenir la première grande économie décarbonée avec des transports propres',
    ministere: 'MTE',
    nomAncienneReformePrioritaire: 'Verdir le parc automobile',
    trigramme: 'VPA',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 2,
    avancement: 0.65,
  },
  {
    id: 10,
    nom: 'Poursuivre la  mise en place des zones à faibles émissions',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Devenir la première grande économie décarbonée avec des transports propres',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Instaurer des zones à faibles émissions (ZFE) opérationnelles dans les territoires en dépassement',
    trigramme: 'ZFE',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 4,
    avancement: 0.78,
  },
  {
    id: 11,
    nom: "Accélérer la rénovation énergétique de l'habitat avec MaPrimeRenov et France renov (guichet unique)",
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'En finir avec les passoires thermiques et renforcer la performance énergétique des bâtiments ',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Accélérer la rénovation énergétique des logements',
    trigramme: 'REL',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 4,
    avancement: 0.94,
  },
  {
    id: 12,
    nom: 'Lutter contre le gaspillage non alimentaire et renforcer le recyclage, notamment du plastique',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: "Réduire les déchets et développer massivement l'économie circulaire",
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Mettre en œuvre la sortie du plastique à usage unique et mieux lutter contre le gaspillage',
    trigramme: 'PUU',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 3,
    avancement: 0.14,
  },
  {
    id: 13,
    nom: "Mettre en œuvre l'objectif  \"Zéro artificialisation nette\"",
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Protéger et restaurer la nature, les écosystèmes et les espèces',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: "Lutter contre l'artificialisation des sols et contre l'étalement urbain",
    trigramme: 'LAS',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 4,
    avancement: 0.98,
  },
  {
    id: 14,
    nom: 'Protéger les espaces naturels ',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Protéger et restaurer la nature, les écosystèmes et les espèces',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Renforcer la protection des espaces naturels',
    trigramme: 'PEN',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 2,
    avancement: 0.05,
  },
  {
    id: 15,
    nom: 'Assurer le bien-être des animaux ',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: 'Protéger et restaurer la nature, les écosystèmes et les espèces',
    ministere: 'MASA',
    nomAncienneReformePrioritaire: 'Améliorer le bien être animal',
    trigramme: 'BEA',
    precedentMinistereResponsable: "Ministère de l'Agriculture et de l'Alimentation",
    meteo: 3,
    avancement: 0.48,
  },
  {
    id: 16,
    nom: 'Garantir 50% de produits bio, de qualité ou durables dans la restauration collective (Egalim)',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: "Permettre l'accès à une alimentation locale et de qualité ",
    ministere: 'MASA',
    nomAncienneReformePrioritaire: 'Garantir 50% de produits bio, de qualité ou durables dans la restauration collective',
    trigramme: 'BIO',
    precedentMinistereResponsable: "Ministère de l'Agriculture et de l'Alimentation",
    meteo: 1,
    avancement: 0.47,
  },
  {
    id: 17,
    nom: 'Renforcer la pêche durable française',
    axe: 'REUSSIR LA TRANSITION ECOLOGIQUE ET ALLER VERS LA NEUTRALITE CARBONE',
    ppg: "Permettre l'accès à une alimentation locale et de qualité ",
    ministere: 'SE MER',
    nomAncienneReformePrioritaire: 'Accompagner la filière pêche pour une exploitation plus durable des ressources',
    trigramme: 'PED',
    precedentMinistereResponsable: '',
    meteo: 4,
    avancement: 0.91,
  },
  {
    id: 18,
    nom: 'Améliorer le niveau des élèves dans les savoirs fondamentaux',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: 'Faire réussir les élèves dans une école des savoirs fondamentaux qui favorise l’épanouissement et qui protège nos enfants',
    ministere: 'MENJ',
    nomAncienneReformePrioritaire: "Améliorer le niveau d'apprentissage en fin de CP / CE1",
    trigramme: 'ANA',
    precedentMinistereResponsable: "Ministère de l'Education Nationale",
    meteo: 1,
    avancement: 0.38,
  },
  {
    id: 19,
    nom: 'Dédoubler les classes en éducation prioritaire et limiter les effectifs à 24 partout ailleurs (grande section, CP, CE1)',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: 'Faire réussir les élèves dans une école des savoirs fondamentaux qui favorise l’épanouissement et qui protège nos enfants',
    ministere: 'MENJ',
    nomAncienneReformePrioritaire: 'Dédoubler les classes en REP (grande section, CP, CE1)',
    trigramme: 'REP',
    precedentMinistereResponsable: "Ministère de l'Education Nationale",
    meteo: 1,
    avancement: 0.33,
  },
  {
    id: 20,
    nom: 'Remplacemer les enseignants absents',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: 'Faire réussir les élèves dans une école des savoirs fondamentaux qui favorise l’épanouissement et qui protège nos enfants',
    ministere: 'MENJ',
    nomAncienneReformePrioritaire: 'Assurer le remplacement des enseignants absents',
    trigramme: 'REA',
    precedentMinistereResponsable: "Ministère de l'Education Nationale",
    meteo: 3,
    avancement: 0.41,
  },
  {
    id: 21,
    nom: "Améliorer l'orientation des lycéens vers l'enseignement supérieur via ParcourSup",
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Refonder l'orientation des élèves",
    ministere: 'MESR',
    nomAncienneReformePrioritaire: 'Déployer Parcoursup',
    trigramme: 'SUP',
    precedentMinistereResponsable: "Ministère de l'Enseignement supérieur, recherche et innovation Enseignement supérieur de la Recherche et de l'Innovation",
    meteo: 4,
    avancement: 0.24,
  },
  {
    id: 22,
    nom: "Rendre l'école plus inclusive",
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Rendre l'école plus inclusive",
    ministere: 'MENJ',
    nomAncienneReformePrioritaire: 'Offrir une scolarisation inclusive et adaptée à tous les enfants handicapés',
    trigramme: 'DEI',
    precedentMinistereResponsable: "Ministère de l'Education Nationale",
    meteo: 3,
    avancement: 0.63,
  },
  {
    id: 23,
    nom: 'Poursuivre le déploiement du Pass Culture',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Faciliter pour chaque jeune l'accès à la culture, au patrimoine et à la création contemporaine",
    ministere: 'MC',
    nomAncienneReformePrioritaire: 'Déployer le pass Culture',
    trigramme: 'DPC',
    precedentMinistereResponsable: 'Ministère de la Culture',
    meteo: 1,
    avancement: 0.91,
  },
  {
    id: 24,
    nom: 'Offrir à chaque enfant une éducation culturelle et artistique',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Faciliter pour chaque jeune l'accès à la culture, au patrimoine et à la création contemporaine",
    ministere: 'MC',
    nomAncienneReformePrioritaire: 'Offrir à chaque enfant une éducation artistique et culturelle',
    trigramme: 'EAC',
    precedentMinistereResponsable: 'Ministère de la Culture',
    meteo: 3,
    avancement: 0.23,
  },
  {
    id: 25,
    nom: 'Valoriser et conserver les patrimoines anciens et contemporains ( PPG =  chantier)',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: 'Soutenir la création française et valoriser le patrimoine dans les environnements physiques et numériques',
    ministere: 'MC',
    nomAncienneReformePrioritaire: 'Préserver le patrimoine architectural français',
    trigramme: 'PAF',
    precedentMinistereResponsable: 'Ministère de la Culture',
    meteo: 4,
    avancement: 0.53,
  },
  {
    id: 26,
    nom: 'Accélérer le renouvellement urbain des quartiers',
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Garantir l'égalité des chances dans l'ensemble des territoires",
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Accélérer le renouvellement urbain des quartiers',
    trigramme: 'UQP',
    precedentMinistereResponsable: 'Ministère de la Cohésion des territoires et des Relations avec les collectivités territoriales',
    meteo: 2,
    avancement: 0.63,
  },
  {
    id: 27,
    nom: "Faire d'Action Cœur de ville et de Petites villes de demain un outil d'aménagement durable du territoire",
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: "Garantir l'égalité des chances dans l'ensemble des territoires",
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Déployer le programme Action Cœur de ville',
    trigramme: 'ACV',
    precedentMinistereResponsable: 'Ministère de la Cohésion des territoires et des Relations avec les collectivités territoriales',
    meteo: 2,
    avancement: 0.92,
  },
  {
    id: 28,
    nom: "Renforcer l'égalité homme / femme dans les entreprises",
    axe: "GARANTIR L'ÉGALITÉ DES CHANCES ET FAVORISER L'EXCELLENCE",
    ppg: 'Porter la grande cause du quinquennat, l’égalité entre les hommes et les femmes',
    ministere: 'MTPEI',
    nomAncienneReformePrioritaire: "Garantir l'égalité professionnelle entre les femmes et les hommes",
    trigramme: 'GEP',
    precedentMinistereResponsable: "Ministère du Travail de l'Emploi et de l'Insertion",
    meteo: 2,
    avancement: 0.81,
  },
  {
    id: 29,
    nom: 'Lutter contre les inégalités concernant la santé des enfants et des femmes  (maintien des 1000 jours dans le périmètre à arbitrer)',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Renforcer la place de la prévention dans le quotidien des Français',
    ministere: 'MSP',
    nomAncienneReformePrioritaire: "Mieux accompagner les mères en périnatalité, dans le cadre des 1000 premiers jours de l'enfant",
    trigramme: 'MPN',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 3,
    avancement: 0.76,
  },
  {
    id: 30,
    nom: 'Améliorer la couverture vaccinale des Français ',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Renforcer la place de la prévention dans le quotidien des Français',
    ministere: 'MSP',
    nomAncienneReformePrioritaire: 'Assurer le déploiement de la vaccination obligatoire',
    trigramme: 'DVO',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 2,
    avancement: 0.6,
  },
  {
    id: 31,
    nom: 'Développer la télésanté notamment au service des patients ayant des maladies chroniques et pour les soins urgents non programmés',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Lutter contre les inégalités d’accès à la santé et les déserts médicaux',
    ministere: 'MSP',
    nomAncienneReformePrioritaire: 'Développer le numérique en santé ',
    trigramme: 'ENP',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 3,
    avancement: 0.57,
  },
  {
    id: 32,
    nom: "Améliorer l'accès aux soins dans tous les territoires",
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Lutter contre les inégalités d’accès à la santé et les déserts médicaux',
    ministere: 'MSP',
    nomAncienneReformePrioritaire: 'Doubler les structures de soins coordonnés',
    trigramme: 'DMS',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 3,
    avancement: 0.92,
  },
  {
    id: 33,
    nom: 'Lutter contre les impayés de pension alimentaire',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Soutenir plus fortement les familles monoparentales',
    ministere: 'MSAPH',
    nomAncienneReformePrioritaire: 'Lutter contre les impayés de pensions alimentaires',
    trigramme: 'IPA',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 2,
    avancement: 0.06,
  },
  {
    id: 34,
    nom: "Garantir un logement pour les sans-abris (Logement d'abord)",
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: "Améliorer l'accès au logement",
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Offrir un logement aux sans-abris (mise en œuvre du plan logement d’abord)',
    trigramme: 'LDA',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 3,
    avancement: 0.52,
  },
  {
    id: 35,
    nom: 'Simplifier l’accès aux droits pour les personnes handicapées',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Faciliter le quotidien des personnes en situation de handicap',
    ministere: 'MSAPH',
    nomAncienneReformePrioritaire: 'Simplifier l’accès aux droits pour les personnes handicapées',
    trigramme: 'DPH',
    precedentMinistereResponsable: "Secrétariat d'Etat chargé des Personnes Handicapées",
    meteo: 3,
    avancement: 0.46,
  },
  {
    id: 36,
    nom: 'Déployer Ma prime adapt',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Bien vieillir à domicile et dans des EHPAD modernisés',
    ministere: 'MTECT',
    nomAncienneReformePrioritaire: 'Améliorer et développer l’offre de logements adaptés aux personnes âgées',
    trigramme: 'LAH',
    precedentMinistereResponsable: 'Ministère de la Transition Ecologique',
    meteo: 3,
    avancement: 0.92,
  },
  {
    id: 37,
    nom: 'Mieux accompagner les aidants',
    axe: 'PRENDRE SOIN DES FRANÇAIS',
    ppg: 'Bien vieillir à domicile et dans des EHPAD modernisés',
    ministere: 'MSAPH',
    nomAncienneReformePrioritaire: 'Mieux accompagner les aidants',
    trigramme: 'MAA',
    precedentMinistereResponsable: 'Ministère des Solidarités et de la Santé',
    meteo: 1,
    avancement: 0.67,
  },
  {
    id: 38,
    nom: "Renforcer la présence par les forces de l'ordre dans l'espace public",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Renforcer la sécurité du quotidien avec davantage de moyens',
    ministere: 'MIOM',
    nomAncienneReformePrioritaire: 'Renforcer la sécurité du quotidien',
    trigramme: 'RSQ',
    precedentMinistereResponsable: "Ministère de l'Intérieur",
    meteo: 3,
    avancement: 0.46,
  },
  {
    id: 39,
    nom: "Associer les parties prenantes à l'amélioration continue du service rendu par les forces de l'ordre (SP+)",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Renforcer la sécurité du quotidien avec davantage de moyens',
    ministere: 'MIOM',
    nomAncienneReformePrioritaire: '',
    trigramme: '',
    precedentMinistereResponsable: '',
    meteo: 3,
    avancement: 0.57,
  },
  {
    id: 40,
    nom: 'Renforcer la lutte contre le trafic de stupéfiants  ',
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Renforcer la sécurité du quotidien avec davantage de moyens',
    ministere: 'MIOM',
    nomAncienneReformePrioritaire: 'Lutter contre les stupéfiants',
    trigramme: 'RLS',
    precedentMinistereResponsable: "Ministère de l'Intérieur",
    meteo: 2,
    avancement: 0.86,
  },
  {
    id: 41,
    nom: "Réformer l'organisation de l'asile",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: "Lutter contre l'immigration illégale et mieux intégrer les étrangers en situation régulière",
    ministere: 'MIOM',
    nomAncienneReformePrioritaire: "Réduire le délai d'instruction des demandes d'asile",
    trigramme: 'IDA',
    precedentMinistereResponsable: "Ministère de l'Intérieur",
    meteo: 3,
    avancement: 1,
  },
  {
    id: 42,
    nom: "Obtenir une désicion d'aide juridictionnelle en moins de 5 jours",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Rendre et exécuter des décisions de justice plus rapidement',
    ministere: 'MJ',
    nomAncienneReformePrioritaire: "Simplifier l'accès à l'aide juridictionnelle",
    trigramme: 'SAJ',
    precedentMinistereResponsable: 'Ministère de la Justice',
    meteo: 4,
    avancement: 0.24,
  },
  {
    id: 43,
    nom: 'Généraliser et approfondir la numérisation de la procédure pénale ',
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Rendre et exécuter des décisions de justice plus rapidement',
    ministere: 'MJ',
    nomAncienneReformePrioritaire: 'Mettre en œuvre la procédure pénale numérique',
    trigramme: 'PPN',
    precedentMinistereResponsable: 'Ministère de la Justice',
    meteo: 1,
    avancement: 0.29,
  },
  {
    id: 44,
    nom: "Améliorer l'exécution des TIG - Développer les places de TIG",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Favoriser la prise en charge et l’insertion des personnes condamnés et des mineurs délinquants',
    ministere: 'MJ',
    nomAncienneReformePrioritaire: 'Développer les places de TIG',
    trigramme: 'TIG',
    precedentMinistereResponsable: 'Ministère de la Justice',
    meteo: 4,
    avancement: 0.02,
  },
  {
    id: 45,
    nom: "Développer l'insertion professionnelle des personnes détenues",
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Favoriser la prise en charge et l’insertion des personnes condamnés et des mineurs délinquants',
    ministere: 'MJ',
    nomAncienneReformePrioritaire: 'Déployer la justice de la vie quotidienne',
    trigramme: 'JVQ',
    precedentMinistereResponsable: 'Ministère de la Justice',
    meteo: 3,
    avancement: 0.24,
  },
  {
    id: 46,
    nom: 'Mieux protéger et accompagner les femmes victimes de violences ',
    axe: 'PROTÉGER LES FRANÇAIS ET GARANTIR LEUR SÉCURITÉ ',
    ppg: 'Lutter contre les violences faites aux femmes et les féminicides',
    ministere: 'MEFH',
    nomAncienneReformePrioritaire: 'Lutter contre les violences faites aux femmes',
    trigramme: 'LVF',
    precedentMinistereResponsable: 'Ministère de l’Égalité entre les femmes et les hommes, de la Diversité et de l’Égalité des chances',
    meteo: 2,
    avancement: 0.29,
  },
  {
    id: 47,
    nom: 'Déployer Services Publics + pour améliorer le service rendu aux Français en associant les usagers',
    axe: 'TRANSFORMER NOS SERVICES PUBLICS ET CONSTRUIRE UNE RENAISSANCE DEMOCRATIQUE',
    ppg: "Simplifier l'accès aux SP dans tous les territoires ",
    ministere: 'MTFP',
    nomAncienneReformePrioritaire: "Améliorer la qualité du service rendu à l'usager",
    trigramme: 'PSP',
    precedentMinistereResponsable: 'Ministère de la Transformation et de la Fonction Publique',
    meteo: 1,
    avancement: 0.57,
  },
  {
    id: 48,
    nom: 'Consolider le réseau des espaces France services',
    axe: 'TRANSFORMER NOS SERVICES PUBLICS ET CONSTRUIRE UNE RENAISSANCE DEMOCRATIQUE',
    ppg: "Simplifier l'accès aux SP dans tous les territoires ",
    ministere: 'MTFP',
    nomAncienneReformePrioritaire: 'Déployer une offre France Services dans tous les territoires',
    trigramme: 'OFS',
    precedentMinistereResponsable: 'Ministère de la Cohésion des territoires et des Relations avec les collectivités territoriales',
    meteo: 2,
    avancement: 0.83,
  },
  {
    id: 49,
    nom: "Poursuivre l'unification du recouvrement social et fiscal",
    axe: 'TRANSFORMER NOS SERVICES PUBLICS ET CONSTRUIRE UNE RENAISSANCE DEMOCRATIQUE',
    ppg: 'Simplifier la vie des PME et des TPE et les accompagner pour faire face aux grandes transitions',
    ministere: 'MEFSIN',
    nomAncienneReformePrioritaire: 'Poursuivre l’unification du recouvrement fiscal et social',
    trigramme: 'RFS',
    precedentMinistereResponsable: "Ministère de l'Economie des Finances et de la Relance",
    meteo: 2,
    avancement: 0.85,
  },
  {
    id: 50,
    nom: "Favoriser l'engagement civique des jeunes ",
    axe: 'TRANSFORMER NOS SERVICES PUBLICS ET CONSTRUIRE UNE RENAISSANCE DEMOCRATIQUE',
    ppg: 'Déployer le service national universel',
    ministere: 'MENJ',
    nomAncienneReformePrioritaire: 'Développer l’engagement citoyen',
    trigramme: 'SPA',
    precedentMinistereResponsable: "Ministère de l'Education Nationale",
    meteo: 3,
    avancement: 0,
  },
];