import {
  metadata_indicateur,
  metadata_indicateur_valeur_acceptee,
} from "@prisma/client";
import { prisma } from "@/server/db/prisma";

const metadataIndicateurs: Omit<metadata_indicateur, "valeurs_acceptees">[] = [
  // METADATA_INDICATEURS - Table metadata_indicateurs_hidden
  {
    name: "indic_id",
    data_type: "text",
    description: "Identifiant de l'indicateur",
    est_visible: true,
    alias: "indic_id",
    est_editable: false,
    validation_regex: "^IND-\\d{3,4}$",
    validation_regex_error_message:
      "Le code de l'indicateur doit être au format 'IND-XXX' ou 'IND-XXXX'",
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_parent_indic",
    data_type: "text",
    description: "Indicateur parent",
    est_visible: true,
    alias: "Indicateur parent",
    est_editable: true,
    validation_regex: "^IND-\\d{3,4}$",
    validation_regex_error_message:
      "Le code de l'indicateur parent doit être au format 'IND-XXX' ou 'IND-XXXX'",
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_parent_ch",
    data_type: "text",
    description: "Code du chantier associé à cet indicateur, au format CH-XXX.",
    est_visible: true,
    alias: "Chantier associé",
    est_editable: true,
    validation_regex: "^CH-\\d{3}$",
    validation_regex_error_message:
      "Le code du chantier parent doit être au format 'CH-XXX'",
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_nom",
    data_type: "text",
    description: "Nom complet de l'indicateur",
    est_visible: true,
    alias: "Nom",
    est_editable: true,
    validation_regex: ".*",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_nom_baro",
    data_type: "text",
    description:
      "Nom de cet indicateur dans le baromètre (si différent de l'intitulé Pilote)",
    est_visible: true,
    alias: "Nom baromètre",
    est_editable: true,
    validation_regex: ".*",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_descr",
    data_type: "text",
    description: "Description de l'indicateur",
    est_visible: true,
    alias: "Description",
    est_editable: true,
    validation_regex: ".*",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_descr_baro",
    data_type: "text",
    description:
      "Description de l'indicateur dans le baromètre (si différent de la description Pilote)",
    est_visible: true,
    alias: "Description baromètre",
    est_editable: true,
    validation_regex: ".*",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_is_perseverant",
    data_type: "boolean",
    description: "Indique si l'indicateur est perseverant",
    est_visible: true,
    alias: "Persévérant",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_is_phare",
    data_type: "boolean",
    description: "Indique si l'indicateur est phare",
    est_visible: true,
    alias: "Phare",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_is_baro",
    data_type: "boolean",
    description:
      "Indicateur présent dans le baromètre des résultats de l'action publique",
    est_visible: true,
    alias: "Baromètre",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_type",
    data_type: "text",
    description:
      "Typologie de l'indicateur.\n\nIl peut s'agir d'indicateur d'impact ('IMPACT'), de déploiement ('DEPL'), de contexte ('CONTEXTE'), de qualité de service ('Q_SERV') ou de rebond ('REBOND').",
    est_visible: true,
    alias: "Typologie",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message:
      "Veuillez choisir une typologie d'indicateur valide parmi: ",
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_source",
    data_type: "text",
    description: "Source déclarée des données de l'indicateur",
    est_visible: true,
    alias: "Source",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "Pas de source renseignée",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_source_url",
    data_type: "text",
    description:
      "URL de la source de donnée déclarée (si accessible publiquement)",
    est_visible: true,
    alias: "Source (URL)",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_methode_calcul",
    data_type: "text",
    description: "Méthode de calcul pour l'obtention des données.",
    est_visible: true,
    alias: "Méthode de calcul",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_unite",
    data_type: "text",
    description:
      "Visible dans Pilote - A renseigner uniquement si pourcentage, heures, mois, milliers, millions, milliards …",
    est_visible: true,
    alias: "Unité",
    est_editable: true,
    validation_regex: ".*",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_hidden_pilote",
    data_type: "boolean",
    description:
      "Indique si l'indicateur est affiché dans Pilote. **Ne fonctionne pas**",
    est_visible: true,
    alias: "Masqué",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "indic_schema",
    data_type: "text",
    description:
      "Nom du schema associé. Cela permet la restriction de la saisie de données.",
    est_visible: true,
    alias: "Contraintes",
    est_editable: false,
    validation_regex: "",
    validation_regex_error_message:
      "Veuillez choisir des contraintes de saisie parmi: ",
    edit_box_type: "multi-select",
    default_value: "sans-contraintes.json",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },
  {
    name: "zg_applicable",
    data_type: "text",
    description:
      "*Zone-group* applicable à cet indicateur. Voir `metadata_zonegroup`",
    est_visible: true,
    alias: "Restriction géographique",
    est_editable: true,
    validation_regex: "ZG-\\d\\d\\d",
    validation_regex_error_message:
      "Le code de la ZG doit être au format 'ZG-XXX'",
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS",
    bloc_id: null,
  },

  // METADATA_PARAMETRAGE_INDICATEURS
  {
    name: "vi_dept_from",
    data_type: "text",
    description:
      "Source des valeurs initiales départementales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur initiale - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "vi_dept_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VI",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "va_dept_from",
    data_type: "text",
    description:
      "Source des valeurs actuelles départementales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur actuelle - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "va_dept_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VA",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "vc_dept_from",
    data_type: "text",
    description:
      "Source des valeurs cibles départementales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur cible - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "vc_dept_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VC",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 2,
  },
  {
    name: "vi_reg_from",
    data_type: "text",
    description:
      "Source des valeurs initiales régionales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur initiale - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "vi_reg_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VI",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "va_reg_from",
    data_type: "text",
    description:
      "Source des valeurs actuelles régionales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur actuelle - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "va_reg_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VA",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "vc_reg_from",
    data_type: "text",
    description:
      "Source des valeurs cibles régionales (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur cible - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "vc_reg_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VC",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 3,
  },
  {
    name: "vi_nat_from",
    data_type: "text",
    description:
      "Source de la valeur initiale nationale (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur initiale - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "vi_nat_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VI",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "va_nat_from",
    data_type: "text",
    description:
      "Source de la valeur actuelle nationale (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur actuelle - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "va_nat_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VA",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "vc_nat_from",
    data_type: "text",
    description:
      "Source de la valeur cible nationale (import, agrégation géographique, agrégation d'indicateurs...)",
    est_visible: true,
    alias: "Valeur cible - Origine",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "vc_nat_op",
    data_type: "text",
    description:
      "Opération effectuée sur la source de la valeur pour obtenir la valeur affichée dans Pilote",
    est_visible: true,
    alias: "Méthode d'agrégation - VC",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 4,
  },
  {
    name: "param_vaca_decumul_from",
    data_type: "text",
    description:
      "Dans le cas où les valeurs sont agrégeables et doivent être décumulées pour calcul de la VAC dans le TA annuel.",
    est_visible: true,
    alias: "Décumul des valeurs saisies (TA annuel)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "param_vaca_partition_date",
    data_type: "text",
    description:
      "Les valeurs sont saisies décumulées ou sont décumulées (Décumul des valeurs saisies = Oui). Un traitement doit-il être appliqué sur ces valeurs ?",
    est_visible: true,
    alias: "Cumul des valeurs (TA annuel)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "param_vaca_op",
    data_type: "text",
    description:
      'Indiquer s\'il faut faire une somme ou une moyenne des VA. Si la VA doit être utilisée telle que saisie, indiquer "Valeur saisie".',
    est_visible: true,
    alias: "Opération (TA annuel)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "param_vacg_decumul_from",
    data_type: "text",
    description:
      "Dans le cas où les valeurs sont agrégeables et doivent être décumulées pour calcul de la VAC dans le TA global. Par défaut, saisir le même paramétrage que pour le TA annuel.",
    est_visible: true,
    alias: "Décumul des valeurs saisies (TA global)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "param_vacg_partition_date",
    data_type: "text",
    description:
      "Les valeurs sont saisies décumulées ou sont décumulées (Décumul des valeurs saisies = Oui). Un traitement doit-il être appliqué sur ces valeurs ?",
    est_visible: true,
    alias: "Cumul des valeurs (TA global)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "param_vacg_op",
    data_type: "text",
    description:
      'Indiquer s\'il faut faire une somme ou une moyenne des VA. Si la VA doit être utilisée telle que saisie, indiquer "Valeur saisie".',
    est_visible: true,
    alias: "Opération (TA global)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "tendance",
    data_type: "text",
    description:
      "Evolution attendue de l'indicateur. Si l'évolution attendue est stable, l'option \"hausse\" sera sélectionnée.",
    est_visible: true,
    alias: "Tendance de l'indicateur",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "HAUSSE",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 5,
  },
  {
    name: "poids_pourcent_nat_declaree",
    data_type: "number",
    description:
      "Poids de l'indicateur dans le calcul du taux d'avancement global aux différentes mailles",
    est_visible: true,
    alias: "Maille nationale",
    est_editable: true,
    validation_regex: "(^\\d{1,2}$)|(^\\d{1,2}\\.\\d{1,2}$)|(^100$)",
    validation_regex_error_message: "Pondération comprise entre 0 et 100.",
    edit_box_type: "text",
    default_value: "0",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 6,
  },
  {
    name: "poids_pourcent_reg_declaree",
    data_type: "number",
    description:
      "Poids de l'indicateur dans le calcul du taux d'avancement global à la maille régionale si territorialisé à cette maille.",
    est_visible: true,
    alias: "Maille régionale",
    est_editable: true,
    validation_regex: "(^\\d{1,2}$)|(^\\d{1,2}\\.\\d{1,2}$)|(^100$)",
    validation_regex_error_message: "Pondération comprise entre 0 et 100.",
    edit_box_type: "text",
    default_value: "0",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 6,
  },
  {
    name: "poids_pourcent_dept_declaree",
    data_type: "number",
    description:
      "Poids de l'indicateur dans le calcul du taux d'avancement global à la maille départementale si territorialisé à cette maille.",
    est_visible: true,
    alias: "Maille départementale",
    est_editable: true,
    validation_regex: "(^\\d{1,2}$)|(^\\d{1,2}\\.\\d{1,2}$)|(^100$)",
    validation_regex_error_message: "Pondération comprise entre 0 et 100.",
    edit_box_type: "text",
    default_value: "0",
    est_obligatoire: false,
    doit_afficher_la_description: false,
    groupe: "METADATA_PARAMETRAGE_INDICATEURS",
    bloc_id: 6,
  },

  // METADATA_INDICATEURS_COMPLEMENTAIRE
  {
    name: "reforme_prioritaire",
    data_type: "text",
    description: "Réforme prioritaire dont est issu l'indicateur persévérant.",
    est_visible: true,
    alias: "Réforme prioritaire",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "projet_annuel_perf",
    data_type: "boolean",
    description:
      "Utilisation de l'indicateur dans le cadre d'un projet annuel de performance (PAP) annexé à un projet de loi de finances.",
    est_visible: true,
    alias: "Projet annuel de performance (PAP)",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "detail_projet_annuel_perf",
    data_type: "text",
    description:
      "Détail du projet annuel de performance dans le cadre duquel l'indicateur est utilisé.",
    est_visible: true,
    alias: "Détail projet annuel de performance",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "periodicite",
    data_type: "text",
    description: "Rythme de production des données de l'indicateur.",
    est_visible: true,
    alias: "Périodicité",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: true,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "delai_disponibilite",
    data_type: "number",
    description:
      "Délai prévisionnel moyen entre la fin de la période couverte par la donnée et la disponibilité de l'indicateur dans PILOTE. A exprimer en nombre seul. L'unité est le mois.",
    est_visible: true,
    alias: "Délai de disponibilité",
    est_editable: true,
    validation_regex: "(^\\d{1,2}$)|(^\\d{1,2}\\.\\d{1,2}$)|(^100$)",
    validation_regex_error_message:
      "Délai de disponibilité compris entre 0 et 100.",
    edit_box_type: "text",
    default_value: "0",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "indic_territorialise",
    data_type: "boolean",
    description:
      "Déclinaison de l'indicateur et de ses cibles aux mailles départementale et/ou régionale.",
    est_visible: true,
    alias: "Territorialisation",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 1,
  },
  {
    name: "frequence_territoriale",
    data_type: "number",
    description:
      "Fréquence d'actualisation des données territoriales, si différente de la fréquence nationale. A exprimer en nombre seul. L'unité est le mois.",
    est_visible: true,
    alias: "Fréquence d'actualisation territoriale",
    est_editable: true,
    validation_regex: "(^\\d{1,2}$)|(^\\d{1,2}\\.\\d{1,2}$)|(^100$)",
    validation_regex_error_message:
      "Fréquence d'actualisation comprise entre 0 et 100.",
    edit_box_type: "text",
    default_value: "0",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "mailles",
    data_type: "text",
    description:
      "Mailles données pour lesquelles les données peuvent être fournies",
    est_visible: true,
    alias: "Mailles données",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "admin_source",
    data_type: "text",
    description:
      "Administration responsable de la diffusion et publication des données",
    est_visible: true,
    alias: "Administration source",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "methode_collecte",
    data_type: "text",
    description: "Méthode de collecte de la donnée",
    est_visible: true,
    alias: "Collecte",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "si_source",
    data_type: "text",
    description: "Système d'information source.",
    est_visible: true,
    alias: "SI source",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "donnee_ouverte",
    data_type: "boolean",
    description: "Accessibilité des données au public.",
    est_visible: true,
    alias: "Donnée ouverte",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "false",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "modalites_donnee_ouverte",
    data_type: "text",
    description: "Modalités d'accès à la donnée si donnée ouverte.",
    est_visible: true,
    alias: "Modalités",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "resp_donnees",
    data_type: "text",
    description:
      "Prénom et nom du responsable données auprès du directeur de projet.",
    est_visible: true,
    alias: "Responsable données",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "resp_donnees_email",
    data_type: "text",
    description:
      "Adresse email du responsable données auprès du directeur de projet.",
    est_visible: true,
    alias: "Email responsable données",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "contact_technique",
    data_type: "text",
    description:
      "Prénom et nom du contact technique au sein de l'unité de diffusion et de publication de la donnée",
    est_visible: true,
    alias: "Contact technique",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "contact_technique_email",
    data_type: "text",
    description:
      "Adresse email du contact technique au sein de l'unité de diffusion et de publication de la donnée",
    est_visible: true,
    alias: "Email contact technique",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "text",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "commentaire",
    data_type: "text",
    description: "Champ de commentaire libre",
    est_visible: true,
    alias: "Commentaire",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "textarea",
    default_value: "",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 7,
  },
  {
    name: "maille_pilotage",
    data_type: "text",
    description:
      "Maille de pilotage de l'indicateur. Maille la plus fine à laquelle des valeurs cibles sont attendues.",
    est_visible: true,
    alias: "Maille de pilotage",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "_",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 2,
  },
  {
    name: "cible_attendue",
    data_type: "boolean",
    description:
      "Avec cible : l'indicateur a vocation à atteindre une cible / sans cible : l'indicateur n'est comparé à aucune valeur de référence. Il s'agit des indicateurs de contexte et de certains indicateurs déclarés sans cible (par conseillers).",
    est_visible: true,
    alias: "Cible attendue",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: null,
    default_value: "true",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 2,
  },
  {
    name: "couverture_temporelle",
    data_type: "text",
    description:
      "Période couverte par la valeur de l'indicateur. Période sur laquelle s'appuie l'observation pour le calcul de l'indicateur.",
    est_visible: true,
    alias: "Couverture temporelle",
    est_editable: true,
    validation_regex: "",
    validation_regex_error_message: null,
    edit_box_type: "multi-select",
    default_value: "continue",
    est_obligatoire: false,
    doit_afficher_la_description: true,
    groupe: "METADATA_INDICATEURS_COMPLEMENTAIRE",
    bloc_id: 2,
  },
];

// Valeurs acceptées pour les champs multi-select
const valeursAcceptees: Omit<metadata_indicateur_valeur_acceptee, "id">[] = [
  // indic_type
  {
    metadata_indicateur_name: "indic_type",
    ordre: 0,
    valeur: "",
    nom: "Choisir une typologie",
    description: "Choisir une typologie",
  },
  {
    metadata_indicateur_name: "indic_type",
    ordre: 1,
    valeur: "IMPACT",
    nom: "Impact",
    description: "Indicateur d'impact",
  },
  {
    metadata_indicateur_name: "indic_type",
    ordre: 2,
    valeur: "DEPL",
    nom: "Déploiement",
    description: "Indicateur de déploiement",
  },
  {
    metadata_indicateur_name: "indic_type",
    ordre: 3,
    valeur: "CONTEXTE",
    nom: "De contexte",
    description: "Indicateur de contexte",
  },
  {
    metadata_indicateur_name: "indic_type",
    ordre: 4,
    valeur: "Q_SERV",
    nom: "De qualité de service",
    description: "Mesure la qualité du service rendu.",
  },
  {
    metadata_indicateur_name: "indic_type",
    ordre: 5,
    valeur: "REBOND",
    nom: "Effets rebonds",
    description: "Effets rebonds engendrés par la mise en place du chantier",
  },

  // indic_schema
  {
    metadata_indicateur_name: "indic_schema",
    ordre: 1,
    valeur: "sans-contraintes.json",
    nom: "-",
    description: "Pas de contraintes particulières",
  },
  {
    metadata_indicateur_name: "indic_schema",
    ordre: 2,
    valeur: "restrict-dept.json",
    nom: "Saisie départementale",
    description: "Saisie restreinte au niveau départemental",
  },
  {
    metadata_indicateur_name: "indic_schema",
    ordre: 3,
    valeur: "restrict-reg.json",
    nom: "Saisie régionale",
    description: "Saisie restreinte au niveau régional",
  },
  {
    metadata_indicateur_name: "indic_schema",
    ordre: 4,
    valeur: "restrict-0-100.json",
    nom: "Dans [0,100]",
    description: "Saisie entre 0 et 100.",
  },

  // zg_applicable - Restrictions géographiques (liste complète)
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 1,
    valeur: "",
    nom: "Toutes zones",
    description: "Toutes zones",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 2,
    valeur: "ZG-002",
    nom: "Façades maritimes département",
    description: "Départements avec façade maritime",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 3,
    valeur: "ZG-003",
    nom: "Façades maritimes région",
    description: "Régions avec façade maritime",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 4,
    valeur: "ZG-004",
    nom: "ZFE département",
    description: "Départements avec au moins une ZFE",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 5,
    valeur: "ZG-005",
    nom: "ZFE région",
    description: "Régions avec au moins une ZFE",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 6,
    valeur: "ZG-006",
    nom: "Façades maritimes hors OM",
    description: "Ensemble des territoires avec façade maritime hors Outre-Mer",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 7,
    valeur: "ZG-007",
    nom: "ZFE",
    description: "Territoires avec au moins une ZFE",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 8,
    valeur: "ZG-008",
    nom: "Ports CH-049",
    description: "Ports de la PPG « Verdir les ports et les flottes »",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 9,
    valeur: "ZG-009",
    nom: "Ports CH-059",
    description: "Ports de la PPG « Devenir leader de l'hydrogène décarboné »",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 10,
    valeur: "ZG-010",
    nom: "Façade maritime Méditerranée",
    description: "Territoires de la façade maritime méditerranéenne",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 11,
    valeur: "ZG-011",
    nom: "ANRU",
    description:
      "Territoires concernés par le programme Accélérer le renouvellement urbain des quartiers",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 12,
    valeur: "ZG-012",
    nom: "ACV",
    description: "Territoires concernés par le programme Action Coeur de Ville",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 13,
    valeur: "ZG-013",
    nom: "PVD",
    description:
      "Territoires concernés par le programme Petites Villes de Demain",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 14,
    valeur: "ZG-014",
    nom: "Outre-Mer",
    description: "DROM",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 15,
    valeur: "ZG-015",
    nom: "Façades maritimes dont OM",
    description: "Territoires avec façade maritime dont Outre-Mer",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 16,
    valeur: "ZG-016",
    nom: "Prisons",
    description:
      "Territoires concernés par le programme 15 000 places de prisons",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 17,
    valeur: "ZG-017",
    nom: "GUDA",
    description: "Territoires concernés par les GUDA",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 18,
    valeur: "ZG-018",
    nom: "Toutes zones sauf Mayotte",
    description: "Tous départements et régions Hexagone et OM, hors Mayotte",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 19,
    valeur: "ZG-019",
    nom: "Toutes zones métropole",
    description: "Tous départements et régions Hexagone",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 20,
    valeur: "ZG-020",
    nom: "50 sites + émetteurs",
    description: "Territoires des 50 sites industriels les plus émetteurs",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 21,
    valeur: "ZG-021",
    nom: "Force aux Frontières",
    description: "Territoires de la PPG « Force aux Frontières »",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 22,
    valeur: "ZG-022",
    nom: "Stationnement vélo sécurisé en gare",
    description:
      "Territoires de l'indicateur Places de stationnement vélo sécurisé en gare (IND-215) de la PPG « Amplifier le plan vélo »",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 23,
    valeur: "ZG-023",
    nom: "Industrie décarbonnée",
    description:
      "Régions de la PPG « Devenir la première grande économie décarbonée »",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 24,
    valeur: "ZG-024",
    nom: "Education prioritaire",
    description:
      "Territoires contenant des écoles en Education Prioritaire (Cantal,Haute-Loire,Lot et Lozère n'ont pas de REP)",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 25,
    valeur: "ZG-025",
    nom: "Bon état écologique des cours d'eau",
    description:
      "Toutes zones sauf départements 09, 64, 75, 93 et DROM (pas de station de mesure)",
  },
  {
    metadata_indicateur_name: "zg_applicable",
    ordre: 26,
    valeur: "ZG-026",
    nom: "PCAET (CH-161)",
    description: "Toutes zones sauf Lozère",
  },

  // vi_dept_from, va_dept_from, vc_dept_from
  {
    metadata_indicateur_name: "vi_dept_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vi_dept_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vi_dept_from",
    ordre: 3,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "va_dept_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "va_dept_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "va_dept_from",
    ordre: 3,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "vc_dept_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vc_dept_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vc_dept_from",
    ordre: 3,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },

  // vi_dept_op, va_dept_op, vc_dept_op
  {
    metadata_indicateur_name: "vi_dept_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vi_dept_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs des sous-indicateurs",
  },
  {
    metadata_indicateur_name: "vi_dept_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs des sous-indicateurs",
  },
  {
    metadata_indicateur_name: "va_dept_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "va_dept_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs des sous-indicateurs",
  },
  {
    metadata_indicateur_name: "va_dept_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs des sous-indicateurs",
  },
  {
    metadata_indicateur_name: "vc_dept_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vc_dept_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs des sous-indicateurs",
  },
  {
    metadata_indicateur_name: "vc_dept_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs des sous-indicateurs",
  },

  // vi_reg_from, va_reg_from, vc_reg_from
  {
    metadata_indicateur_name: "vi_reg_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vi_reg_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vi_reg_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "vi_reg_from",
    ordre: 4,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "va_reg_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "va_reg_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "va_reg_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "va_reg_from",
    ordre: 4,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "vc_reg_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vc_reg_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vc_reg_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "vc_reg_from",
    ordre: 4,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },

  // vi_reg_op, va_reg_op, vc_reg_op
  {
    metadata_indicateur_name: "vi_reg_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vi_reg_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vi_reg_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "va_reg_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "va_reg_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "va_reg_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vc_reg_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vc_reg_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vc_reg_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },

  // vi_nat_from, va_nat_from, vc_nat_from
  {
    metadata_indicateur_name: "vi_nat_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vi_nat_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vi_nat_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "vi_nat_from",
    ordre: 4,
    valeur: "REG",
    nom: "Depuis les REG",
    description: "Cette valeur sera aggrégée depuis les valeurs régionales.",
  },
  {
    metadata_indicateur_name: "vi_nat_from",
    ordre: 5,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "va_nat_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "va_nat_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "va_nat_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "va_nat_from",
    ordre: 4,
    valeur: "REG",
    nom: "Depuis les REG",
    description: "Cette valeur sera aggrégée depuis les valeurs régionales.",
  },
  {
    metadata_indicateur_name: "va_nat_from",
    ordre: 5,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },
  {
    metadata_indicateur_name: "vc_nat_from",
    ordre: 1,
    valeur: "_",
    nom: "Pas de saisie",
    description: "Pas de saisie attendue à cette maille",
  },
  {
    metadata_indicateur_name: "vc_nat_from",
    ordre: 2,
    valeur: "user_input",
    nom: "Saisie utilisateur",
    description: "On attend que cette valeur soit saisie par l'utilisateur",
  },
  {
    metadata_indicateur_name: "vc_nat_from",
    ordre: 3,
    valeur: "DEPT",
    nom: "Depuis les DEPT",
    description:
      "Cette valeur sera aggrégée depuis les valeurs départementales",
  },
  {
    metadata_indicateur_name: "vc_nat_from",
    ordre: 4,
    valeur: "REG",
    nom: "Depuis les REG",
    description: "Cette valeur sera aggrégée depuis les valeurs régionales.",
  },
  {
    metadata_indicateur_name: "vc_nat_from",
    ordre: 5,
    valeur: "sub_indic",
    nom: "Sous-indicateur",
    description: "",
  },

  // vi_nat_op, va_nat_op, vc_nat_op
  {
    metadata_indicateur_name: "vi_nat_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vi_nat_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vi_nat_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "va_nat_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "va_nat_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "va_nat_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vc_nat_op",
    ordre: 1,
    valeur: "_",
    nom: "Aucune",
    description: "Pas d'opération d'aggrégation",
  },
  {
    metadata_indicateur_name: "vc_nat_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme",
    description: "Somme des valeurs de la maille inférieure.",
  },
  {
    metadata_indicateur_name: "vc_nat_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne des valeurs de la maille inférieure.",
  },

  // param_vaca_decumul_from
  {
    metadata_indicateur_name: "param_vaca_decumul_from",
    ordre: 1,
    valeur: "_",
    nom: "Non",
    description: "Pas de décumul nécessaire",
  },
  {
    metadata_indicateur_name: "param_vaca_decumul_from",
    ordre: 2,
    valeur: "from_year_start",
    nom: "Oui, saisie en cumul annuel",
    description: "Les valeurs sont saisies cumulées depuis le débur d'année",
  },
  {
    metadata_indicateur_name: "param_vaca_decumul_from",
    ordre: 3,
    valeur: "from_custom_date::2019-01-01",
    nom: "Oui, saisie en cumul depuis le début",
    description:
      "Les valeurs ont saisies cumulées depuis une date éloignée, date de VI ou début du dispositif.",
  },

  // param_vaca_partition_date
  {
    metadata_indicateur_name: "param_vaca_partition_date",
    ordre: 1,
    valeur: "_",
    nom: "Non",
    description: "Valeurs déjà cumulées ou non cumulables.",
  },
  {
    metadata_indicateur_name: "param_vaca_partition_date",
    ordre: 2,
    valeur: "from_year_start",
    nom: "Oui, cumul annuel",
    description: "Cumul des VA depuis janvier (01) de l'année en cours.",
  },
  {
    metadata_indicateur_name: "param_vaca_partition_date",
    ordre: 3,
    valeur: "from_custom_date::2019-01-01",
    nom: "Oui, cumul global",
    description: "Cumul de toutes les VA.",
  },
  {
    metadata_indicateur_name: "param_vaca_partition_date",
    ordre: 4,
    valeur: "from_previous_month::12",
    nom: "Oui, cumul en année glissante",
    description: "Cumul des VA des 12 derniers mois.",
  },

  // param_vaca_op
  {
    metadata_indicateur_name: "param_vaca_op",
    ordre: 0,
    valeur: "",
    nom: "Choisir une Opération (TA annuel)",
    description: "Choisir une Opération (TA annuel)",
  },
  {
    metadata_indicateur_name: "param_vaca_op",
    ordre: 1,
    valeur: "current_value",
    nom: "Valeur saisie",
    description:
      "VA saisie : non cumulable (%) ou déjà cumulée (valeur à date)",
  },
  {
    metadata_indicateur_name: "param_vaca_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme des VA",
    description: "Somme des VA",
  },
  {
    metadata_indicateur_name: "param_vaca_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne",
  },

  // param_vacg_decumul_from
  {
    metadata_indicateur_name: "param_vacg_decumul_from",
    ordre: 1,
    valeur: "_",
    nom: "Non",
    description: "Pas de décumul nécessaire",
  },
  {
    metadata_indicateur_name: "param_vacg_decumul_from",
    ordre: 2,
    valeur: "from_year_start",
    nom: "Oui, saisie en cumul annuel",
    description: "Les valeurs sont saisies cumulées depuis le débur d'année",
  },
  {
    metadata_indicateur_name: "param_vacg_decumul_from",
    ordre: 3,
    valeur: "from_custom_date::2019-01-01",
    nom: "Oui, saisie en cumul depuis le début",
    description:
      "Les valeurs ont saisies cumulées depuis une date éloignée, date de VI ou début du dispositif.",
  },

  // param_vacg_partition_date
  {
    metadata_indicateur_name: "param_vacg_partition_date",
    ordre: 1,
    valeur: "_",
    nom: "Non",
    description: "Valeurs déjà cumulées ou non cumulables.",
  },
  {
    metadata_indicateur_name: "param_vacg_partition_date",
    ordre: 2,
    valeur: "from_year_start",
    nom: "Oui, cumul annuel",
    description: "Cumul des VA depuis janvier (01) de l'année en cours.",
  },
  {
    metadata_indicateur_name: "param_vacg_partition_date",
    ordre: 3,
    valeur: "from_custom_date::2019-01-01",
    nom: "Oui, cumul global",
    description: "Cumul de toutes les VA.",
  },
  {
    metadata_indicateur_name: "param_vacg_partition_date",
    ordre: 4,
    valeur: "from_previous_month::12",
    nom: "Oui, cumul en année glissante",
    description: "Cumul des VA des 12 derniers mois.",
  },

  // param_vacg_op
  {
    metadata_indicateur_name: "param_vacg_op",
    ordre: 0,
    valeur: "",
    nom: "Choisir une Opération (TA global)",
    description: "Choisir une Opération (TA global)",
  },
  {
    metadata_indicateur_name: "param_vacg_op",
    ordre: 1,
    valeur: "current_value",
    nom: "Valeur saisie",
    description:
      "VA saisie : non cumulable (%) ou déjà cumulée (valeur à date)",
  },
  {
    metadata_indicateur_name: "param_vacg_op",
    ordre: 2,
    valeur: "sum",
    nom: "Somme des VA",
    description: "Somme des VA",
  },
  {
    metadata_indicateur_name: "param_vacg_op",
    ordre: 3,
    valeur: "moy",
    nom: "Moyenne",
    description: "Moyenne",
  },

  // tendance
  {
    metadata_indicateur_name: "tendance",
    ordre: 1,
    valeur: "HAUSSE",
    nom: "Hausse",
    description: "Tendance en hausse",
  },
  {
    metadata_indicateur_name: "tendance",
    ordre: 2,
    valeur: "BAISSE",
    nom: "Baisse",
    description: "Tendance en baisse",
  },

  // periodicite
  {
    metadata_indicateur_name: "periodicite",
    ordre: 0,
    valeur: "",
    nom: "Choisir une périodicité",
    description: "Choisir une périodicité",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 1,
    valeur: "Mensuelle",
    nom: "Mensuelle",
    description: "Périodicité mensuelle",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 2,
    valeur: "Bimestrielle",
    nom: "Bimestrielle",
    description: "Tous les 2 mois",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 3,
    valeur: "Trimestrielle",
    nom: "Trimestrielle",
    description: "Périodicité trimestrielle",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 4,
    valeur: "Semestrielle",
    nom: "Semestrielle",
    description: "Périodicité semestrielle",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 5,
    valeur: "Annuelle",
    nom: "Annuelle",
    description: "Périodicité annuelle",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 6,
    valeur: "Bi-annuelle",
    nom: "Bi-annuelle",
    description: "Périodicité bi-annuelle",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 7,
    valeur: "3 ans",
    nom: "3 ans",
    description: "Périodicité triennale",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 8,
    valeur: "6 ans",
    nom: "6 ans",
    description: "Périodicité sexennale",
  },
  {
    metadata_indicateur_name: "periodicite",
    ordre: 9,
    valeur: "Autre/Inconnue",
    nom: "Autre/Inconnue",
    description: "Périodicité autre/inconnue",
  },

  // mailles
  {
    metadata_indicateur_name: "mailles",
    ordre: 1,
    valeur: "NAT",
    nom: "Nationale",
    description: "Maille nationale",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 2,
    valeur: "REG",
    nom: "Régions",
    description: "Maille régionale",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 3,
    valeur: "DEPT",
    nom: "Départements",
    description: "Maille départementale",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 4,
    valeur: "COM",
    nom: "Communes",
    description: "Maille communale",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 5,
    valeur: "FAC_M",
    nom: "Façades maritimes",
    description: "Façades maritimes",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 6,
    valeur: "EPCI",
    nom: "EPCI",
    description: "Etablissement Public de Coopération Intercommunale",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 7,
    valeur: "AGGLO",
    nom: "Agglomérations",
    description:
      "Agglomérations de plus de 150 000 habitants en France métropolitaine",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 8,
    valeur: "DISP",
    nom: "DISP",
    description: "Directions inter-régionales des services pénitentiaires",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 9,
    valeur: "COUR",
    nom: "Cours d'appel",
    description: "Cours d'appel",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 10,
    valeur: "DIRPJJ",
    nom: "DIRPJJ",
    description:
      "Directions inter-régionales de la protection judiciaire de la jeunesse",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 11,
    valeur: "ACA",
    nom: "Académies",
    description: "Académies",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 12,
    valeur: "PORT",
    nom: "Grands ports maritimes",
    description: "Grands ports maritimes",
  },
  {
    metadata_indicateur_name: "mailles",
    ordre: 13,
    valeur: "MEAE",
    nom: "Zones MEAE",
    description: "Zones géographiques regroupant plusieurs pays",
  },

  // maille_pilotage
  {
    metadata_indicateur_name: "maille_pilotage",
    ordre: 1,
    valeur: "_",
    nom: "Non piloté",
    description:
      "Indicateur non utilisé pour le pilotage, sans cible attendue.",
  },
  {
    metadata_indicateur_name: "maille_pilotage",
    ordre: 2,
    valeur: "DEPT",
    nom: "Départemental",
    description: "Pilotage départemental, régional et national",
  },
  {
    metadata_indicateur_name: "maille_pilotage",
    ordre: 3,
    valeur: "REG",
    nom: "Régional",
    description: "Pilotage régional et national",
  },
  {
    metadata_indicateur_name: "maille_pilotage",
    ordre: 4,
    valeur: "NAT",
    nom: "National",
    description: "Pilotage national",
  },

  // couverture_temporelle
  {
    metadata_indicateur_name: "couverture_temporelle",
    ordre: 1,
    valeur: "continue",
    nom: "Période d'observation",
    description:
      "Valeur mesurée depuis le début de la période d'observation. Par exemple, depuis une date précise de lancement du programme.",
  },
  {
    metadata_indicateur_name: "couverture_temporelle",
    ordre: 2,
    valeur: "a_date",
    nom: "A date",
    description: "Calcul de l'indicateur à date.",
  },
  {
    metadata_indicateur_name: "couverture_temporelle",
    ordre: 3,
    valeur: "annee",
    nom: "Année",
    description:
      "Indicateur observé depuis le début de l'année civile en cours.",
  },
  {
    metadata_indicateur_name: "couverture_temporelle",
    ordre: 4,
    valeur: "annee_glissante",
    nom: "Année glissante",
    description: "Indicateur observé sur les 12 derniers mois.",
  },
];

async function run() {
  await prisma.metadata_indicateur_valeur_acceptee.deleteMany();
  await prisma.metadata_indicateur.deleteMany();

  // Upsert metadata indicateurs
  for (const metadata of metadataIndicateurs) {
    await prisma.metadata_indicateur.upsert({
      where: { name: metadata.name },
      create: metadata,
      update: metadata,
    });
  }

  // Upsert valeurs acceptées
  for (const valeur of valeursAcceptees) {
    await prisma.metadata_indicateur_valeur_acceptee.upsert({
      where: {
        metadata_indicateur_name_ordre: {
          metadata_indicateur_name: valeur.metadata_indicateur_name,
          ordre: valeur.ordre,
        },
      },
      create: valeur,
      update: valeur,
    });
  }

  // eslint-disable-next-line no-console
  console.log("✅ Seed metadata indicateurs terminé avec succès");
}

run()
  .catch((error) => {
    // eslint-disable-next-line no-console
    console.error("❌ Erreur lors du seed:", error);
    throw error;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
