FROM postgres:14.6-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nano \
    openssh-client \
    curl \
 && rm -rf /var/lib/apt/lists/*

RUN curl -O https://cli-dl.scalingo.com/install && bash install

WORKDIR /root/.ssh

# Copy if files exist
COPY docker/id_rsa_scaling[o] id_rsa
COPY docker/id_rsa_scalingo.pu[b] id_rsa.pub

WORKDIR /app
