FROM python:3.9.16

# [setup.root-dir]
WORKDIR /app/data_management

# [install.postgres]
# RUN apt-get update && apt-get install -y \
    # postgresql \
#  && rm -rf /var/lib/apt/lists/*



## [install.pipenv] (last version)
RUN python -m pip install --no-cache pipenv

## [install.pipenv-deps]
COPY data_management/Pipfile .
COPY data_management/Pipfile.lock .

# Install exact versions of Pipfile.lock with "pipenv sync"
RUN pipenv sync
## [log] Show path of env just created
RUN pipenv --venv
## [log] Show versions of packages installed in env just created
RUN pipenv run pip freeze


# [setup.dbt] Install dbt deps
# COPY data_management/data_factory data_factory/
# COPY data_management/profiles.yml .

# RUN pipenv run dbt deps --project-dir data_factory 
# RUN rm -rf data_factory/
# RUN rm -rf profiles.yml

#COPY data_management/. .



#ENV PIPENV_PIPFILE=/app/$DATA_DIR/Pipfile
# Start entrypoint.sh script
# VOLUME  ["/app/data_management/data_factory"]
# WORKDIR /app/data_management/data_factory
RUN mkdir -p data_factory
WORKDIR /app/data_management/data_factory

ENTRYPOINT ["pipenv","run"]

CMD ["/bin/bash", "../../docker/entrypoint.datajobs.dev.sh"]

#CMD ["scripts/serve_doc.sh"]
