version: 2

models:
  - name: chantier
    description: "Une vue sur `df3_chantier`"
    columns:
      - name: id
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: nom
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: code_insee
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: taux_avancement
        description: "source de données à date du 06/07/2023 : dfakto.fact_progress_chantier"
      - name: taux_avancement_date
        description: "Date du TA. C'est la date la plus récente de màj d'un indicateur du TA chantier."
      - name: territoire_nom
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_zone"
      - name: perimetre_ids
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: maille
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_zone"
      - name: directeurs_administration_centrale
        description: "source de données à date du 06/07/2023 : ppg_metadata.m_porteurs"
      - name: ministeres
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: directions_administration_centrale
        description: "source de données à date du 06/07/2023 : ppg_metadata.m_porteurs"
      - name: directeurs_projet
        description: "source de données à date du 06/07/2023 : ppg_metadata.m_porteurs"
      - name: meteo
        description: "source de données à date du 06/07/2023 : champs déprécié"
      - name: axe
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_axe"
      - name: ppg
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_ppg"
      - name: directeurs_projet_mails
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: est_barometre
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: est_territorialise
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_chantier"
      - name: territoire_code
        description: "source de données à date du 06/07/2023 : ppg_metadata.view_meta_zone"
      - name: taux_avancement_precedent
        description: "source de données à date du 06/07/2023 : données non encore existante"
      - name: values_replicated_from
        description: "Indique la maille depuis laquelle la valeur est répliquée. Dans `{reg, nat}`. En effet, on ne peut pas répliquer des valeurs depuis la maille `DEPT` car il n'y a pas de maille inférieure."
      - name: cible_attendue
        description: "Indique si une cible et donc un TA sont attendus pour ce chantier. Si non renseignée dans `ch_cible_attendue` (cf table source `metadata_chantiers`), alors on considère sa valeur à `TRUE`."
  - name: axe
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_axe"
      - name: nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_axe"
  - name: ppg
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_ppg"
      - name: nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_ppg"
  - name: commentaire
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : identifiant uniques"
      - name: chantier_id
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: type
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: contenu
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: date
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: auteur
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: maille
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: code_insee
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
  - name: indicateur
    description: "Une vue sur `df3_indicateur`"
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: chantier_id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: objectif_valeur_cible
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: objectif_taux_avancement
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: objectif_date_valeur_cible
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: type_id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: type_nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.ref_indic_type"
      - name: est_barometre
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: est_phare
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: date_valeur_actuelle
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: date_valeur_initiale
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: valeur_actuelle
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: valeur_initiale
        description: "source de données à date du 07/07/2023 : dfakto.fact_progress"
      - name: code_insee
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_zone"
      - name: maille
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_zone"
      - name: territoire_nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_zone"
      - name: evolution_valeur_actuelle
        description: "source de données à date du 07/07/2023 : dfakto.fact_financials"
      - name: evolution_date_valeur_actuelle
        description: "source de données à date du 07/07/2023 : ppg_metadata.fact_financials"
      - name: description
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: source
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: mode_de_calcul
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_indicateur"
      - name: territoire_code
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_zone"
      - name: ponderation_declaree
        description: "Pondération déclarée pour cette zone (déclarée pour la maille)"
      - name: ponderation_reel
        description: "Pondération réelle calculée"
      - name: dernier_import_date
        description: "Date dernier import de données pour cet {indicateur-zone}"
      - name: dernier_import_rapport_id
        description: "UUID du dernier rapport d'import de données pour cet {indicateur-zone}"
      - name: dernier_import_date_indic
        description: "Date dernier import de données pour cet {indicateur}"
      - name: dernier_import_rapport_id_indic
        description: "UUID du dernier rapport d'import de données pour cet {indicateur}"
      - name: dernier_import_auteur
        description: "Auteur du dernier rapport qui modifie cet indicateur sur cette zone"
      - name: dernier_import_auteur_indic
        description: "Auteur du dernier rapport pour cet {indicateur} (sur n'importe quelle zone)"
      - name: prochaine_date_maj
        description: "Date attendue de prochaine date de mise à jour de l'indicateur. Peut être dans le passé si la mise à jour est en retard. `NULL` si indicateur non applicable sur cette zone."
      - name: prochaine_date_valeur_actuelle
        description: "Date de la prochaine VA si les imports de données se font selon la périodicité déclarée. `NULL` si indicateur non applicable sur cette zone."
      - name: prochaine_date_maj_jours
        description: "Nombre de jours avant la prochaine mise à jour théorique de l'indicateur. Peut être négatif si la mise à jour est en retard. `NULL` si indicateur non applicable sur cette zone."
      - name: est_a_jour
        description: "Indique si les données sont à jour par rapport à la périodicité théorique déclarée de mise à jour. `NULL` si indicateur non applicable sur cette zone."
      - name: tendance
        description : "Indique si l'indicateur a une tendance en hausse ou en baisse (valeur HAUSSE / BAISSE)"
  - name: decision_strategique
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : identifiant unique"
      - name: auteur
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: type_decision_strategique
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: contenu
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: date
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: chantier_id
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
  - name: ministere
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : ppg_metadata.m_porteurs"
      - name: nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.m_porteurs"
      - name: icone
        description: "source de données à date du 07/07/2023 : ppg_metadata.m_porteurs"
  - name: objectif
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : identifiant unique"
      - name: auteur
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: type_objectif
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: contenu
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: date
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
      - name: chantier_id
        description: "source de données à date du 07/07/2023 : import massif des commentaires"
  - name: perimetre
    columns:
      - name: id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_perimetre"
      - name: nom
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_perimetre"
      - name: ministere
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_perimetre"
      - name: ministere_id
        description: "source de données à date du 07/07/2023 : ppg_metadata.view_meta_perimetre"
