// TODO supprimer et faire passer en serverSideProps
const départements = [
  {
    codeInsee: '01',
    nom: 'Ain',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '02',
    nom: 'Aisne',
    sousTerritoires: [],
    codeInseeParent: '32',
  },
  {
    codeInsee: '03',
    nom: 'Allier',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '04',
    nom: 'Alpes-de-Haute-Provence',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '05',
    nom: 'Hautes-Alpes',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '06',
    nom: 'Alpes-Maritimes',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '07',
    nom: 'Ardèche',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '08',
    nom: 'Ardennes',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '09',
    nom: 'Ariège',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '10',
    nom: 'Aube',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '11',
    nom: 'Aude',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '12',
    nom: 'Aveyron',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '13',
    nom: 'Bouches-du-Rhône',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '14',
    nom: 'Calvados',
    sousTerritoires: [],
    codeInseeParent: '28',
  },
  {
    codeInsee: '15',
    nom: 'Cantal',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '16',
    nom: 'Charente',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '17',
    nom: 'Charente-Maritime',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '18',
    nom: 'Cher',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '19',
    nom: 'Corrèze',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '21',
    nom: "Côte-d'Or",
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '22',
    nom: "Côtes-d'Armor",
    sousTerritoires: [],
    codeInseeParent: '53',
  },
  {
    codeInsee: '23',
    nom: 'Creuse',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '24',
    nom: 'Dordogne',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '25',
    nom: 'Doubs',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '26',
    nom: 'Drôme',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '27',
    nom: 'Eure',
    sousTerritoires: [],
    codeInseeParent: '28',
  },
  {
    codeInsee: '28',
    nom: 'Eure-et-Loir',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '29',
    nom: 'Finistère',
    sousTerritoires: [],
    codeInseeParent: '53',
  },
  {
    codeInsee: '2A',
    nom: 'Corse-du-Sud',
    sousTerritoires: [],
    codeInseeParent: '94',
  },
  {
    codeInsee: '2B',
    nom: 'Haute-Corse',
    sousTerritoires: [],
    codeInseeParent: '94',
  },
  {
    codeInsee: '30',
    nom: 'Gard',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '31',
    nom: 'Haute-Garonne',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '32',
    nom: 'Gers',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '33',
    nom: 'Gironde',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '34',
    nom: 'Hérault',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '35',
    nom: 'Ille-et-Vilaine',
    sousTerritoires: [],
    codeInseeParent: '53',
  },
  {
    codeInsee: '36',
    nom: 'Indre',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '37',
    nom: 'Indre-et-Loire',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '38',
    nom: 'Isère',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '39',
    nom: 'Jura',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '40',
    nom: 'Landes',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '41',
    nom: 'Loir-et-Cher',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '42',
    nom: 'Loire',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '43',
    nom: 'Haute-Loire',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '44',
    nom: 'Loire-Atlantique',
    sousTerritoires: [],
    codeInseeParent: '52',
  },
  {
    codeInsee: '45',
    nom: 'Loiret',
    sousTerritoires: [],
    codeInseeParent: '24',
  },
  {
    codeInsee: '46',
    nom: 'Lot',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '47',
    nom: 'Lot-et-Garonne',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '48',
    nom: 'Lozère',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '49',
    nom: 'Maine-et-Loire',
    sousTerritoires: [],
    codeInseeParent: '52',
  },
  {
    codeInsee: '50',
    nom: 'Manche',
    sousTerritoires: [],
    codeInseeParent: '28',
  },
  {
    codeInsee: '51',
    nom: 'Marne',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '52',
    nom: 'Haute-Marne',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '53',
    nom: 'Mayenne',
    sousTerritoires: [],
    codeInseeParent: '52',
  },
  {
    codeInsee: '54',
    nom: 'Meurthe-et-Moselle',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '55',
    nom: 'Meuse',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '56',
    nom: 'Morbihan',
    sousTerritoires: [],
    codeInseeParent: '53',
  },
  {
    codeInsee: '57',
    nom: 'Moselle',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '58',
    nom: 'Nièvre',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '59',
    nom: 'Nord',
    sousTerritoires: [],
    codeInseeParent: '32',
  },
  {
    codeInsee: '60',
    nom: 'Oise',
    sousTerritoires: [],
    codeInseeParent: '32',
  },
  {
    codeInsee: '61',
    nom: 'Orne',
    sousTerritoires: [],
    codeInseeParent: '28',
  },
  {
    codeInsee: '62',
    nom: 'Pas-de-Calais',
    sousTerritoires: [],
    codeInseeParent: '32',
  },
  {
    codeInsee: '63',
    nom: 'Puy-de-Dôme',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '64',
    nom: 'Pyrénées-Atlantiques',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '65',
    nom: 'Hautes-Pyrénées',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '66',
    nom: 'Pyrénées-Orientales',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '67',
    nom: 'Bas-Rhin',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '68',
    nom: 'Haut-Rhin',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '69',
    nom: 'Rhône',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '70',
    nom: 'Haute-Saône',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '71',
    nom: 'Saône-et-Loire',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '72',
    nom: 'Sarthe',
    sousTerritoires: [],
    codeInseeParent: '52',
  },
  {
    codeInsee: '73',
    nom: 'Savoie',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '74',
    nom: 'Haute-Savoie',
    sousTerritoires: [],
    codeInseeParent: '84',
  },
  {
    codeInsee: '75',
    nom: 'Paris',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '76',
    nom: 'Seine-Maritime',
    sousTerritoires: [],
    codeInseeParent: '28',
  },
  {
    codeInsee: '77',
    nom: 'Seine-et-Marne',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '78',
    nom: 'Yvelines',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '79',
    nom: 'Deux-Sèvres',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '80',
    nom: 'Somme',
    sousTerritoires: [],
    codeInseeParent: '32',
  },
  {
    codeInsee: '81',
    nom: 'Tarn',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '82',
    nom: 'Tarn-et-Garonne',
    sousTerritoires: [],
    codeInseeParent: '76',
  },
  {
    codeInsee: '83',
    nom: 'Var',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '84',
    nom: 'Vaucluse',
    sousTerritoires: [],
    codeInseeParent: '93',
  },
  {
    codeInsee: '85',
    nom: 'Vendée',
    sousTerritoires: [],
    codeInseeParent: '52',
  },
  {
    codeInsee: '86',
    nom: 'Vienne',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '87',
    nom: 'Haute-Vienne',
    sousTerritoires: [],
    codeInseeParent: '75',
  },
  {
    codeInsee: '88',
    nom: 'Vosges',
    sousTerritoires: [],
    codeInseeParent: '44',
  },
  {
    codeInsee: '89',
    nom: 'Yonne',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '90',
    nom: 'Territoire de Belfort',
    sousTerritoires: [],
    codeInseeParent: '27',
  },
  {
    codeInsee: '91',
    nom: 'Essonne',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '92',
    nom: 'Hauts-de-Seine',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '93',
    nom: 'Seine-Saint-Denis',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '94',
    nom: 'Val-de-Marne',
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '95',
    nom: "Val-d'Oise",
    sousTerritoires: [],
    codeInseeParent: '11',
  },
  {
    codeInsee: '971',
    nom: 'Guadeloupe',
    sousTerritoires: [],
    codeInseeParent: '01',
  },
  {
    codeInsee: '972',
    nom: 'Martinique',
    sousTerritoires: [],
    codeInseeParent: '02',
  },
  {
    codeInsee: '973',
    nom: 'Guyane',
    sousTerritoires: [],
    codeInseeParent: '03',
  },
  {
    codeInsee: '974',
    nom: 'La Réunion',
    sousTerritoires: [],
    codeInseeParent: '04',
  },
  {
    codeInsee: '976',
    nom: 'Mayotte',
    sousTerritoires: [],
    codeInseeParent: '06',
  },
];

export default départements;
