ditp_ppg_dbt:
  target: prod_with_fal
  outputs:
    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | int }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: public
    local:
      type: duckdb
      path: 'ditp_pilote.duckdb'
    prod_with_fal:
      type: fal
      threads: 1
      db_profile: prod
