import { MetadataIndicateurForm } from "./types";

export const mockMetadataIndicateurs: MetadataIndicateurForm[] = [
  {
    name: "indic_id",
    dataType: "text",
    description: "Identifiant de l'indicateur",
    estVisible: true,
    alias: "indic_id",
    estEditable: false,
    validationRegex: "^IND-\\d{3,4}$",
    metaPiloteEditRegexViolationMessage:
      "Le code de l'indicateur doit être au format 'IND-XXX' ou 'IND-XXXX'",
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: true,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_parent_indic",
    dataType: "text",
    description: "Indicateur parent",
    estVisible: true,
    alias: "Indicateur parent",
    estEditable: true,
    validationRegex: "^IND-\\d{3,4}$",
    metaPiloteEditRegexViolationMessage:
      "Le code de l'indicateur parent doit être au format 'IND-XXX' ou 'IND-XXXX'",
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_parent_ch",
    dataType: "text",
    description: "Code du chantier associé à cet indicateur, au format CH-XXX.",
    estVisible: true,
    alias: "Chantier associé",
    estEditable: true,
    validationRegex: "^CH-\\d{3}$",
    metaPiloteEditRegexViolationMessage:
      "Le code du chantier parent doit être au format 'CH-XXX'",
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: true,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_nom",
    dataType: "text",
    description: "Nom complet de l'indicateur",
    estVisible: true,
    alias: "Nom",
    estEditable: true,
    validationRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: true,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_nom_baro",
    dataType: "text",
    description:
      "Nom de cet indicateur dans le baromètre (si différent de l'intitulé Pilote)",
    estVisible: true,
    alias: "Nom baromètre",
    estEditable: true,
    validationRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_descr",
    dataType: "text",
    description: "Description de l'indicateur",
    estVisible: true,
    alias: "Description",
    estEditable: true,
    validationRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "textarea",
    defaultValue: "",
    estObligatoire: true,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_descr_baro",
    dataType: "text",
    description:
      "Description de l'indicateur dans le baromètre (si différent de la description Pilote)",
    estVisible: true,
    alias: "Description baromètre",
    estEditable: true,
    validationRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "textarea",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_is_perseverant",
    dataType: "boolean",
    description: "Indique si l'indicateur est perseverant",
    estVisible: true,
    alias: "Persévérant",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "boolean",
    defaultValue: false,
    estObligatoire: false,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_is_phare",
    dataType: "boolean",
    description: "Indique si l'indicateur est phare",
    estVisible: true,
    alias: "Phare",
    estEditable: true,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "boolean",
    defaultValue: false,
    estObligatoire: false,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_is_baro",
    dataType: "boolean",
    description:
      "Indicateur présent dans le baromètre des résultats de l'action publique",
    estVisible: true,
    alias: "Baromètre",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "boolean",
    defaultValue: false,
    estObligatoire: false,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_type",
    dataType: "text",
    description:
      "Typologie de l'indicateur.\n\nIl peut s'agir d'indicateur d'impact ('IMPACT'), de déploiement ('DEPL'), de contexte ('CONTEXTE'), de qualité de service ('Q_SERV') ou de rebond ('REBOND').",
    estVisible: true,
    alias: "Typologie",
    estEditable: true,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage:
      "Veuillez choisir une typologie d'indicateur valide parmi: ",
    editBoxType: "multi-select",
    defaultValue: "",
    estObligatoire: true,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [
      {
        ordre: 0,
        value: "",
        name: "Choisir une typologie",
        description: "Choisir une typologie",
      },
      {
        ordre: 1,
        value: "IMPACT",
        name: "Impact",
        description: "Indicateur d'impact",
      },
      {
        ordre: 2,
        value: "DEPL",
        name: "Déploiement",
        description: "Indicateur de déploiement",
      },
      {
        ordre: 3,
        value: "CONTEXTE",
        name: "De contexte",
        description: "Indicateur de contexte",
      },
      {
        ordre: 4,
        value: "Q_SERV",
        name: "De qualité de service",
        description: "Mesure la qualité du service rendu.",
      },
      {
        ordre: 5,
        value: "REBOND",
        name: "Effets rebonds",
        description:
          "Effets rebonds engendrés par la mise en place du chantier",
      },
    ],
  },
  {
    name: "indic_source",
    dataType: "text",
    description: "Source déclarée des données de l'indicateur",
    estVisible: true,
    alias: "Source",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "textarea",
    defaultValue: "Pas de source renseignée",
    estObligatoire: false,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_source_url",
    dataType: "text",
    description:
      "URL de la source de donnée déclarée (si accessible publiquement)",
    estVisible: true,
    alias: "Source (URL)",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: false,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_methode_calcul",
    dataType: "text",
    description: "Méthode de calcul pour l'obtention des données.",
    estVisible: true,
    alias: "Méthode de calcul",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "textarea",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_unite",
    dataType: "text",
    description:
      "Visible dans Pilote - A renseigner uniquement si pourcentage, heures, mois, milliers, millions, milliards …",
    estVisible: true,
    alias: "Unité",
    estEditable: true,
    validationRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "text",
    defaultValue: "",
    estObligatoire: false,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_hidden_pilote",
    dataType: "boolean",
    description:
      "Indique si l'indicateur est affiché dans Pilote. **Ne fonctionne pas**",
    estVisible: true,
    alias: "Masqué",
    estEditable: true,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    editBoxType: "boolean",
    defaultValue: false,
    estObligatoire: true,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [],
  },
  {
    name: "indic_schema",
    dataType: "text",
    description:
      "Nom du schema associé. Cela permet la restriction de la saisie de données.",
    estVisible: true,
    alias: "Contraintes",
    estEditable: false,
    validationRegex: "",
    metaPiloteEditRegexViolationMessage:
      "Veuillez choisir des contraintes de saisie parmi: ",
    editBoxType: "multi-select",
    defaultValue: "sans-contraintes.json",
    estObligatoire: true,
    doitAfficherLaDescription: true,
    listeValeursAcceptes: [
      {
        ordre: 1,
        value: "sans-contraintes.json",
        name: "-",
        description: "Pas de contraintes particulières",
      },
      {
        ordre: 2,
        value: "restrict-dept.json",
        name: "Saisie départementale",
        description: "Saisie restreinte au niveau départemental",
      },
      {
        ordre: 3,
        value: "restrict-reg.json",
        name: "Saisie régionale",
        description: "Saisie restreinte au niveau régional",
      },
      {
        ordre: 4,
        value: "restrict-0-100.json",
        name: "Dans [0,100]",
        description: "Saisie entre 0 et 100.",
      },
    ],
  },
];
