import { MetadataIndicateurForm } from "./types";

export const mockMetadataIndicateurs: MetadataIndicateurForm[] = [
  {
    name: "indic_id",
    dataType: "text",
    description: "Identifiant de l'indicateur",
    metaPiloteShow: true,
    metaPiloteAlias: "indic_id",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "^IND-\\d{3,4}$",
    metaPiloteEditRegexViolationMessage:
      "Le code de l'indicateur doit être au format 'IND-XXX' ou 'IND-XXXX'",
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_parent_indic",
    dataType: "text",
    description: "Indicateur parent",
    metaPiloteShow: true,
    metaPiloteAlias: "Indicateur parent",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: "^IND-\\d{3,4}$",
    metaPiloteEditRegexViolationMessage:
      "Le code de l'indicateur parent doit être au format 'IND-XXX' ou 'IND-XXXX'",
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_parent_ch",
    dataType: "text",
    description: "Code du chantier associé à cet indicateur, au format CH-XXX.",
    metaPiloteShow: true,
    metaPiloteAlias: "Chantier associé",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: "^CH-\\d{3}$",
    metaPiloteEditRegexViolationMessage:
      "Le code du chantier parent doit être au format 'CH-XXX'",
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_nom",
    dataType: "text",
    description: "Nom complet de l'indicateur",
    metaPiloteShow: true,
    metaPiloteAlias: "Nom",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_nom_baro",
    dataType: "text",
    description:
      "Nom de cet indicateur dans le baromètre (si différent de l'intitulé Pilote)",
    metaPiloteShow: true,
    metaPiloteAlias: "Nom baromètre",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_descr",
    dataType: "text",
    description: "Description de l'indicateur",
    metaPiloteShow: true,
    metaPiloteAlias: "Description",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "textarea",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_descr_baro",
    dataType: "text",
    description:
      "Description de l'indicateur dans le baromètre (si différent de la description Pilote)",
    metaPiloteShow: true,
    metaPiloteAlias: "Description baromètre",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "textarea",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_is_perseverant",
    dataType: "boolean",
    description: "Indique si l'indicateur est perseverant",
    metaPiloteShow: true,
    metaPiloteAlias: "Persévérant",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "boolean",
    metaPiloteDefaultValue: false,
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_is_phare",
    dataType: "boolean",
    description: "Indique si l'indicateur est phare",
    metaPiloteShow: true,
    metaPiloteAlias: "Phare",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "boolean",
    metaPiloteDefaultValue: false,
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_is_baro",
    dataType: "boolean",
    description:
      "Indicateur présent dans le baromètre des résultats de l'action publique",
    metaPiloteShow: true,
    metaPiloteAlias: "Baromètre",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "boolean",
    metaPiloteDefaultValue: false,
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_type",
    dataType: "text",
    description:
      "Typologie de l'indicateur.\n\nIl peut s'agir d'indicateur d'impact ('IMPACT'), de déploiement ('DEPL'), de contexte ('CONTEXTE'), de qualité de service ('Q_SERV') ou de rebond ('REBOND').",
    metaPiloteShow: true,
    metaPiloteAlias: "Typologie",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage:
      "Veuillez choisir une typologie d'indicateur valide parmi: ",
    metaPiloteEditBoxType: "multi-select",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: true,
    acceptedValues: [
      {
        orderId: 0,
        value: "",
        name: "Choisir une typologie",
        desc: "Choisir une typologie",
      },
      {
        orderId: 1,
        value: "IMPACT",
        name: "Impact",
        desc: "Indicateur d'impact",
      },
      {
        orderId: 2,
        value: "DEPL",
        name: "Déploiement",
        desc: "Indicateur de déploiement",
      },
      {
        orderId: 3,
        value: "CONTEXTE",
        name: "De contexte",
        desc: "Indicateur de contexte",
      },
      {
        orderId: 4,
        value: "Q_SERV",
        name: "De qualité de service",
        desc: "Mesure la qualité du service rendu.",
      },
      {
        orderId: 5,
        value: "REBOND",
        name: "Effets rebonds",
        desc: "Effets rebonds engendrés par la mise en place du chantier",
      },
    ],
  },
  {
    name: "indic_source",
    dataType: "text",
    description: "Source déclarée des données de l'indicateur",
    metaPiloteShow: true,
    metaPiloteAlias: "Source",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "textarea",
    metaPiloteDefaultValue: "Pas de source renseignée",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_source_url",
    dataType: "text",
    description:
      "URL de la source de donnée déclarée (si accessible publiquement)",
    metaPiloteShow: true,
    metaPiloteAlias: "Source (URL)",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: false,
    acceptedValues: [],
  },
  {
    name: "indic_methode_calcul",
    dataType: "text",
    description: "Méthode de calcul pour l'obtention des données.",
    metaPiloteShow: true,
    metaPiloteAlias: "Méthode de calcul",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "textarea",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_unite",
    dataType: "text",
    description:
      "Visible dans Pilote - A renseigner uniquement si pourcentage, heures, mois, milliers, millions, milliards …",
    metaPiloteShow: true,
    metaPiloteAlias: "Unité",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: ".*",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "text",
    metaPiloteDefaultValue: "",
    metaPiloteMandatory: false,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_hidden_pilote",
    dataType: "boolean",
    description:
      "Indique si l'indicateur est affiché dans Pilote. **Ne fonctionne pas**",
    metaPiloteShow: true,
    metaPiloteAlias: "Masqué",
    metaPiloteEditIsEditable: true,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage: null,
    metaPiloteEditBoxType: "boolean",
    metaPiloteDefaultValue: false,
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: true,
    acceptedValues: [],
  },
  {
    name: "indic_schema",
    dataType: "text",
    description:
      "Nom du schema associé. Cela permet la restriction de la saisie de données.",
    metaPiloteShow: true,
    metaPiloteAlias: "Contraintes",
    metaPiloteEditIsEditable: false,
    metaPiloteEditRegex: "",
    metaPiloteEditRegexViolationMessage:
      "Veuillez choisir des contraintes de saisie parmi: ",
    metaPiloteEditBoxType: "multi-select",
    metaPiloteDefaultValue: "sans-contraintes.json",
    metaPiloteMandatory: true,
    metaPiloteDispDispDesc: true,
    acceptedValues: [
      {
        orderId: 1,
        value: "sans-contraintes.json",
        name: "-",
        desc: "Pas de contraintes particulières",
      },
      {
        orderId: 2,
        value: "restrict-dept.json",
        name: "Saisie départementale",
        desc: "Saisie restreinte au niveau départemental",
      },
      {
        orderId: 3,
        value: "restrict-reg.json",
        name: "Saisie régionale",
        desc: "Saisie restreinte au niveau régional",
      },
      {
        orderId: 4,
        value: "restrict-0-100.json",
        name: "Dans [0,100]",
        desc: "Saisie entre 0 et 100.",
      },
    ],
  },
];
