version: "3.8"

services:
  import_commentaires:
    build: .
    env_file: [.env]
    volumes:
      - "./import.sh/:/app/import.sh"
      - "./import_commentaires.csv/:/app/import_commentaires.csv"
  
