version: 2

models:
  - name: tous_indicateurs
    description: |
        Cette table contient les données des indicateurs au format pour le *Baromètre des résultats de l'action publique*.

        Ce format ne sert que pour cet usage.
    columns:
        - name: indic_id
          description: Identifiant de l'indicateur
        - name: enforce_zone_id
          description: Identifiant de la zone (`zone_id`)
        - name: maille
          description: Maille de la zone (`zone_type`)
        - name: metric_enforce_date
          description: Date de la valeur
        - name: indic_va
          description: Valeur actuelle (VA) de l'indicateur à cette date et pour cette zone
        - name: indic_vi
          description: Valeur initiale (VI) de l'indicateur à cette date et pour cette zone
        - name: indic_vc
          description: Valeur cible (VC) de l'indicateur à cette date et pour cette zone
        - name: indic_ta
          description: Taux d'avancement (TA) de l'indicateur à cette date et pour cette zone
  - name: baro_meta_indicateurs
    description: Informations des indicateurs utiles pour le baromètre
    columns:
        - name: indic_id
          description: Identifiant de l'indicateur
        - name: indic_nom_baro
          description: Nom de l'indicateur dans le baromètre
        - name: indic_descr_baro
          description: Description de l'indicateur dans le baromètre
  - name: baro_meta_chantiers
    description: Informations des chantiers utiles pour le baromètre
    columns:
        - name: chantier_id
          description: Identifiant du chantier
        - name: ch_nom
          description: Nom du chantier (dans Pilote)
        - name: engagement_short
          description: Version courte de l'engagement (ou axe)
