export type TypeEvenement =
  | "VALEUR_CREEE"
  | "VALEUR_MODIFIEE"
  | "VALEUR_HISTORISEE"
  | "PROPOSITION_VALEUR_CREEE"
  | "PROPOSITION_VALEUR_MODIFIEE"
  | "PROPOSITION_VALEUR_SUPPRIMEE"
  | "PROPOSITION_VALEUR_REFUSEE"
  | "PROPOSITION_VALEUR_ACCUSEE_RECEPTION"
  | "PROPOSITION_VALEUR_ACCEPTEE"
  | "PROPOSITION_VALEUR_IGNOREE_VALEUR_MODIFIEE"
  | "PROPOSITION_VALEUR_IGNOREE_VALEUR_HISTORISEE"
  | "PROPOSITION_VALEUR_ACCEPTEE_AVEC_MODIFICATION";
