
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ditp_ppg_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ditp_ppg_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  ditp_ppg_dbt:
    raw:
      +schema: raw_data
      +materialized: table
    staging:
      +schema: raw_data
      +materialized: view
    marts:
      +schema: marts
      faits_indicateur:
        +materialized: incremental
        +unique_key:
          - 'indicateur_id'
          - 'zone_id'
          - 'metric_date'
          - 'metric_type'
          - 'import_date'
      pivot_faits_indicateur:
        +materialized: table
      2_pivot_faits_indicateur:
        pivot_faits_indicateur_toutes_mailles:
          +materialized: table
          +indexes:
            - columns: [ 'indicateur_id' , 'zone_id' ]
      6_calcul_ta_indicateur:
        taux_avancement_indicateur:
          +materialized: table
      7_calcul_ta_chantier:
        taux_avancement_chantier_historique:
          +materialized: view
        taux_avancement_chantier:
          +materialized: table
      8_evolution_indicateur:
        evolution_indicateur:
          +materialized: table
    intermediate:
      +schema: marts
      +materialized: view
    exposition:
      +schema: public
      +materialized: incremental
      axe:
        +unique_key:
          - 'id'
      ministere:
        +unique_key:
          - 'id'
      perimetre:
        +unique_key:
          - 'id'
      ppg:
        +unique_key:
          - 'id'
      chantier:
        +unique_key:
          - 'id'
          - 'maille'
          - 'code_insee'
      indicateur:
        +unique_key:
          - 'id'
          - 'maille'
          - 'code_insee'
      commentaire:
        +unique_key:
          - 'id'
      objectif:
        +unique_key:
          - 'id'
      decision_strategique:
        +unique_key:
          - 'id'
      objectif_projet_structurant:
        +unique_key:
          - 'id'
      synthese_des_resultats:
        +unique_key:
          - 'id'
      synthese_des_resultats_projet_structurant:
        +unique_key:
          - 'id'
      perimetre_projet_structurant:
        +unique_key:
          - 'id'
      commentaire_projet_structurant:
        +unique_key:
          - 'id'
      indicateur_projet_structurant:
        +unique_key:
          - 'id'
      projet_structurant:
        +unique_key:
          - 'id'
