[runtime]
dlthub_telemetry = false

[sources.load_ppg_metadata]
some_key = false

[github_repo]
user = "DITP-pilotage"
repo = "PPG_metadata"

[destination.db_pilote.config]
# target_schema = "raw_data"

[sources.load_ppg_metadata.ppg_metadata_source.csv_to_load.schema.raw_data]
# table_alias = "<path-to-file>"
metadata_axes = "views/axe/view_meta_axe.csv"
metadata_chantier_meteos = "models/chantier/ref_chantier_meteo.csv"
metadata_chantiers = "views/chantier/view_meta_chantier.csv"
metadata_engagement = "models/chantier/ref_chantier_engagement.csv"
metadata_indicateur_types = "models/indicateur/ref_indic_type.csv"
metadata_perimetres_projet_structurant = "views/perimetre/mapping_per_pst.csv"
metadata_perimetres = "views/perimetre/view_meta_perimetre.csv"
metadata_porteurs = "views/porteur/view_meta_porteur.csv"
metadata_ppgs = "views/ppg/view_meta_ppg.csv"
metadata_zonegroup = "models/zone/ref_zone_group.csv"
metadata_zones = "views/zone/view_meta_zone.csv"

[sources.load_ppg_metadata.ppg_metadata_source.csv_to_load.schema.tmp]
# table_alias = "<path-to-file>"
utilisateur_py = "seeds/utilisateur.csv"
commentaires_py = "seeds/commentaires.csv"
mesure_indicateur_py = "seeds/mesure_indicateur.csv"
rapport_import_mesure_indicateur_py = "seeds/rapport_import_mesure_indicateur.csv"
