export type DonneeChantier = {
  id: string;
  nom: string;
  maille: string;
  axe: string;
  territoireCode: string;
  ministèreNom: string | null;
  tauxDAvancementAnnuel: number | null;
  tauxDAvancementNational: number | null;
  tauxDAvancementRégional: number | null;
  tauxDAvancementDépartemental: number | null;
  météo: string;
  directeursProjetIds: string[];
  responsablesLocauxIds: string[];
  statut: string;
  estBaromètre: boolean;
  estTerritorialisé: boolean;
  commActionsÀVenir: string | null;
  commActionsÀValoriser: string | null;
  commFreinsÀLever: string | null;
  commCommentairesSurLesDonnées: string | null;
  commAutresRésultats: string | null;
  commAutresRésultatsNonCorrélésAuxIndicateurs: string | null;
  decStratSuiviDesDécisions: string | null;
  objNotreAmbition: string | null;
  objDéjàFait: string | null;
  objÀFaire: string | null;
  synthèseDesRésultats: string | null;
};
