export const BREVO_TEMPLATE_IDS = {
  PROPOSITION_VALEUR_ACCEPTEE: 40,
  PROPOSITION_VALEUR_ACCEPTEE_AVEC_MODIFICATION: 41,
  PROPOSITION_VALEUR_REFUSEE: 42,
  PROPOSITION_VALEUR_ACCUSEE_RECEPTION: 74,
} as const;
