"""Creation table fact_progress_chantier

Revision ID: ce7cd8885cdc
Revises: 8c26585a5fa7
Create Date: 2022-12-19 16:27:07.122489

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ce7cd8885cdc'
down_revision = '8c26585a5fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_progress_chantier',
                    sa.Column('tree_node_id', sa.VARCHAR(length=32), nullable=False),
                    sa.Column('period_id', sa.INTEGER(), nullable=False),
                    sa.Column('progress', sa.FLOAT(), nullable=False),
                    sa.Column('bounded_progress', sa.FLOAT(), nullable=False),
                    sa.Column('is_representative', sa.BOOLEAN(), nullable=False),
                    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('tree_node_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_progress_chantier', schema='raw_data')
    # ### end Alembic commands ###
