"""Creation table indicateur_type

Revision ID: ea78c5116b09
Revises: d48f466836f4
Create Date: 2022-12-20 11:02:21.182895

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea78c5116b09'
down_revision = 'd48f466836f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicateur_type',
                    sa.Column('indic_type_id', sa.TEXT(), nullable=False),
                    sa.Column('indic_type_name', sa.TEXT(), nullable=False),
                    sa.Column('indic_type_descr', sa.TEXT(), nullable=False),
                    sa.Column('indic_type_rank', sa.TEXT(), nullable=False),
                    sa.PrimaryKeyConstraint('indic_type_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicateur_type', schema='raw_data')
    # ### end Alembic commands ###
