"""creation de la table dim_structures

Revision ID: d48f466836f4
Revises: ce7cd8885cdc
Create Date: 2022-12-19 16:40:14.551328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48f466836f4'
down_revision = 'ce7cd8885cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_structures',
    sa.Column('structure_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('top_level_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('structure_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('structure_is_part_of_update_period', sa.BOOLEAN(), nullable=False),
    sa.Column('structure_scorecard_frequency', sa.VARCHAR(length=7), nullable=True),
    sa.Column('structure_is_hidden', sa.BOOLEAN(), nullable=False),
    sa.Column('structure_has_correction', sa.BOOLEAN(), nullable=False),
    sa.Column('structure_level', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('structure_id'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_structures', schema='raw_data')
    # ### end Alembic commands ###
