"""Creation table metadata_zone

Revision ID: f204b4b3225f
Revises: ff331d893a0b
Create Date: 2022-12-17 23:36:44.238746

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f204b4b3225f'
down_revision = 'ff331d893a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_zone',
                    sa.Column('zone_id', sa.VARCHAR(length=15), nullable=False),
                    sa.Column('nom', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('zone_code', sa.VARCHAR(length=7), nullable=False),
                    sa.Column('zone_type', sa.VARCHAR(length=15), nullable=False),
                    sa.Column('zone_parent', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('zone_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_zone', schema='raw_data')
    # ### end Alembic commands ###
