"""creation_table_metadata_porteur

Revision ID: 1a049e97d770
Revises: ea78c5116b09
Create Date: 2022-12-26 11:01:08.542382

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a049e97d770'
down_revision = 'ea78c5116b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_porteur',
                    sa.Column('porteur_id', sa.VARCHAR(length=4), nullable=False),
                    sa.Column('porteur_short', sa.VARCHAR(length=15), nullable=False),
                    sa.Column('porteur_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('porteur_desc', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('porteur_type_id', sa.VARCHAR(length=2), nullable=True),
                    sa.Column('porteur_type_short', sa.VARCHAR(length=5), nullable=True),
                    sa.Column('porteur_type_name', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('porteur_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_porteur', schema='raw_data')
    # ### end Alembic commands ###
