"""Creation table fact_progress_indicateur

Revision ID: dbfbf78c7f60
Revises: f204b4b3225f
Create Date: 2022-12-19 12:05:53.543670

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dbfbf78c7f60'
down_revision = 'f204b4b3225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_progress_indicateur',
                    sa.Column('tree_node_id', sa.VARCHAR(length=32), nullable=False),
                    sa.Column('effect_id', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('period_id', sa.INTEGER(), nullable=False),
                    sa.Column('tag_applied', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('valeur_initiale', sa.FLOAT(), nullable=True),
                    sa.Column('valeur_actuelle', sa.FLOAT(), nullable=True),
                    sa.Column('valeur_cible', sa.FLOAT(), nullable=True),
                    sa.Column('progress', sa.FLOAT(), nullable=True),
                    sa.Column('bounded_progress', sa.FLOAT(), nullable=True),
                    sa.Column('date_valeur_initiale', sa.DATE(), nullable=True),
                    sa.Column('date_valeur_actuelle', sa.DATE(), nullable=True),
                    sa.Column('date_valeur_cible', sa.DATE(), nullable=True),
                    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('tree_node_id', 'effect_id', 'period_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_progress_indicateur', schema='raw_data')
    # ### end Alembic commands ###
