"""creation de la table dim_tree_nodes

Revision ID: 8c26585a5fa7
Revises: dbfbf78c7f60
Create Date: 2022-12-19 15:46:11.607940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c26585a5fa7'
down_revision = 'dbfbf78c7f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_tree_nodes',
    sa.Column('tree_node_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tree_node_parent_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('structure_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('maturity_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tree_node_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tree_node_code', sa.VARCHAR(length=15), nullable=False),
    sa.Column('tree_node_status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('tree_node_last_synchronization_date', sa.DateTime(), nullable=True),
    sa.Column('tree_node_last_update_properties_date', sa.DateTime(), nullable=False),
    sa.Column('tree_node_last_update_scorecard_date', sa.DateTime(), nullable=True),
    sa.Column('tree_node_last_scorecard_update_by_anybody_date', sa.DateTime(), nullable=True),
    sa.Column('tree_node_last_update_children_date', sa.DateTime(), nullable=True),
    sa.Column('tree_node_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tree_node_id'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_tree_nodes', schema='raw_data')
    # ### end Alembic commands ###
