"""ajout colonne mail directeur projet dans metadata chantier

Revision ID: f8db64c7bbe4
Revises: 85f5a84ec27e
Create Date: 2023-01-17 14:37:48.196007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8db64c7bbe4'
down_revision = '85f5a84ec27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_chantier', sa.Column('ch_dp_mail', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_chantier', 'ch_dp_mail', schema='raw_data')
    # ### end Alembic commands ###
