"""création table fact financials enr

Revision ID: f4b719de05ac
Revises: 4e3581f93ace
Create Date: 2023-01-24 14:25:01.835307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b719de05ac'
down_revision = '4e3581f93ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_financials_enr',
    sa.Column('tree_node_id', sa.TEXT(), nullable=False),
    sa.Column('period_id', sa.TEXT(), nullable=False),
    sa.Column('state_id', sa.TEXT(), nullable=False),
    sa.Column('effect_id', sa.TEXT(), nullable=False),
    sa.Column('financials_decumulated_amount', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('tree_node_id', 'period_id', 'state_id', 'effect_id'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_financials_enr', schema='raw_data')
    # ### end Alembic commands ###
