"""ajout colonnes per_porteur_id et per_porteur_name_short dans metadata perimetre

Revision ID: be28619a17a9
Revises: f8db64c7bbe4
Create Date: 2023-01-18 17:43:49.612756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be28619a17a9'
down_revision = 'f8db64c7bbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_perimetre', sa.Column('per_porteur_id', sa.VARCHAR(length=4), nullable=True), schema='raw_data')
    op.add_column('metadata_perimetre', sa.Column('per_porteur_name_short', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_perimetre', 'per_porteur_name_short', schema='raw_data')
    op.drop_column('metadata_perimetre', 'per_porteur_id', schema='raw_data')
    # ### end Alembic commands ###
