"""creation de la table dim periods

Revision ID: 5bf790485d14
Revises: f4b719de05ac
Create Date: 2023-01-24 15:22:07.499358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf790485d14'
down_revision = 'f4b719de05ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_periods',
    sa.Column('period_id', sa.TEXT(), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('period_year', sa.INTEGER(), nullable=False),
    sa.Column('period_month', sa.TEXT(), nullable=False),
    sa.Column('period_month_tri', sa.TEXT(), nullable=False),
    sa.Column('period_month_year', sa.TEXT(), nullable=False),
    sa.Column('period_month_year_tri', sa.TEXT(), nullable=False),
    sa.Column('period_quarter', sa.TEXT(), nullable=False),
    sa.Column('period_quarter_year', sa.TEXT(), nullable=False),
    sa.Column('period_year_in_time', sa.TEXT(), nullable=True),
    sa.Column('period_month_in_time', sa.TEXT(), nullable=True),
    sa.Column('period_quarter_in_time', sa.TEXT(), nullable=True),
    sa.Column('period_current_year_flag', sa.TEXT(), nullable=True),
    sa.Column('period_current_month_flag', sa.TEXT(), nullable=True),
    sa.Column('period_current_quarter_flag', sa.TEXT(), nullable=True),
    sa.Column('period_last_year_flag', sa.TEXT(), nullable=True),
    sa.Column('period_last_month_flag', sa.TEXT(), nullable=True),
    sa.Column('period_last_quarter_flag', sa.TEXT(), nullable=True),
    sa.Column('period_next_year_flag', sa.TEXT(), nullable=True),
    sa.Column('period_next_month_flag', sa.TEXT(), nullable=True),
    sa.Column('period_next_quarter_flag', sa.TEXT(), nullable=True),
    sa.Column('period_total_flag', sa.TEXT(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('period_id'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_periods', schema='raw_data')
    # ### end Alembic commands ###
