"""Ajout de la table view Data properties

Revision ID: d8592002956c
Revises: e05512f54211
Create Date: 2023-01-12 11:16:15.800797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8592002956c'
down_revision = 'e05512f54211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_data_properties',
    sa.Column('reforme_code', sa.TEXT(), nullable=False),
    sa.Column('region_code', sa.TEXT(), nullable=False),
    sa.Column('academie_code', sa.TEXT(), nullable=True),
    sa.Column('departement_code', sa.TEXT(), nullable=False),
    sa.Column('objectifs_de_la_reforme', sa.TEXT(), nullable=True),
    sa.Column('synthese_des_resultats', sa.TEXT(), nullable=True),
    sa.Column('difficultes_rencontrees_et_risques_anticipes', sa.TEXT(), nullable=True),
    sa.Column('solutions_proposees_et_prochaines_etapes', sa.TEXT(), nullable=True),
    sa.Column('un_exemple_concret_de_reussite_liee_a_la_reforme', sa.TEXT(), nullable=True),
    sa.Column('dernieres_realisations_et_suivi_des_decisions', sa.TEXT(), nullable=True),
    sa.Column('meteo', sa.TEXT(), nullable=True),
    sa.Column('meteo_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('methodologie_de_renseignement_de_la_meteo', sa.TEXT(), nullable=True),
    sa.Column('chef_de_projet_national', sa.TEXT(), nullable=True),
    sa.Column('chef_de_projet_national_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('equipe_projet_donnee_qualitative_utilisateurs', sa.TEXT(), nullable=True),
    sa.Column('equipe_projet_donnee_qualitative_groupe', sa.TEXT(), nullable=True),
    sa.Column('equipe_projet_donnee_quantitative_utilisateurs', sa.TEXT(), nullable=True),
    sa.Column('dac', sa.TEXT(), nullable=True),
    sa.Column('acces_en_consultation_utilisateurs', sa.TEXT(), nullable=True),
    sa.Column('contexte_local', sa.TEXT(), nullable=True),
    sa.Column('feuille_de_route', sa.TEXT(), nullable=True),
    sa.Column('referent_local_groupe', sa.TEXT(), nullable=True),
    sa.Column('reforme_name', sa.TEXT(), nullable=True),
    sa.Column('objectifs_de_la_reforme_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('synthese_des_resultats_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('difficultes_rencontrees_et_risques_anticipes_date_de_mise', sa.DateTime(), nullable=True),
    sa.Column('solutions_proposees_et_prochaines_etapes_date_de_mise_a_jo', sa.DateTime(), nullable=True),
    sa.Column('un_exemple_concret_de_reussite_liee_a_la_reforme_date_de', sa.DateTime(), nullable=True),
    sa.Column('dernieres_realisations_et_suivi_des_decisions_date_de_mise', sa.DateTime(), nullable=True),
    sa.Column('methodologie_de_renseignement_de_la_meteo_date_de_mise_a', sa.DateTime(), nullable=True),
    sa.Column('equipe_projet_donnee_qualitative_utilisateurs_date_de_mise', sa.DateTime(), nullable=True),
    sa.Column('equipe_projet_donnee_qualitative_groupe_date_de_mise_a_jo', sa.DateTime(), nullable=True),
    sa.Column('equipe_projet_donnee_quantitative_utilisateurs_date_de_mis', sa.DateTime(), nullable=True),
    sa.Column('dac_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('acces_en_consultation_utilisateurs_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('contexte_local_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('feuille_de_route_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('referent_local_groupe_date_de_mise_a_jour', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reforme_code', 'region_code', 'departement_code'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_data_properties', schema='raw_data')
    # ### end Alembic commands ###
