"""Ajout de la table chantier meteo

Revision ID: 85f5a84ec27e
Revises: d8592002956c
Create Date: 2023-01-12 11:53:01.692761

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '85f5a84ec27e'
down_revision = 'd8592002956c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chantier_meteo',
                    sa.Column('ch_meteo_id', sa.TEXT(), nullable=False),
                    sa.Column('ch_meteo_name', sa.TEXT(), nullable=True),
                    sa.Column('ch_meteo_descr', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('ch_meteo_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chantier_meteo', schema='raw_data')
    # ### end Alembic commands ###
