"""ajout colonne porteur name short pour la table metadata porteur

Revision ID: e05512f54211
Revises: 0cc024a1de21
Create Date: 2023-01-10 17:17:06.720638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05512f54211'
down_revision = '0cc024a1de21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_porteur', sa.Column('porteur_name_short', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_porteur', 'porteur_name_short', schema='raw_data')
    # ### end Alembic commands ###
