"""Ajout de champs dans la table meteo et indicateur

Revision ID: 4e3581f93ace
Revises: be28619a17a9
Create Date: 2023-01-20 11:18:21.505863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3581f93ace'
down_revision = 'be28619a17a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chantier_meteo', sa.Column('ch_meteo_name_dfakto', sa.TEXT(), nullable=True), schema='raw_data')
    op.add_column('metadata_indicateur', sa.Column('indic_source', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    op.add_column('metadata_indicateur', sa.Column('indic_source_url', sa.TEXT(), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_indicateur', 'indic_source_url', schema='raw_data')
    op.drop_column('metadata_indicateur', 'indic_source', schema='raw_data')
    op.drop_column('chantier_meteo', 'ch_meteo_name_dfakto', schema='raw_data')
    # ### end Alembic commands ###
