"""ajout tables metadata axe et ppg

Revision ID: 0cc024a1de21
Revises: 35c8bfc9c651
Create Date: 2023-01-10 17:00:45.277959

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0cc024a1de21'
down_revision = '35c8bfc9c651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_axe',
                    sa.Column('axe_id', sa.TEXT(), nullable=False),
                    sa.Column('axe_short', sa.TEXT(), nullable=True),
                    sa.Column('axe_name', sa.TEXT(), nullable=True),
                    sa.Column('axe_desc', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('axe_id'),
                    schema='raw_data'
                    )
    op.create_table('metadata_ppg',
                    sa.Column('ppg_id', sa.TEXT(), nullable=False),
                    sa.Column('ppg_axe', sa.TEXT(), nullable=False),
                    sa.Column('ppg_code', sa.TEXT(), nullable=True),
                    sa.Column('ppg_desc', sa.TEXT(), nullable=True),
                    sa.Column('ppg_nom', sa.TEXT(), nullable=False),
                    sa.Column('porteur_shorts', sa.TEXT(), nullable=True),
                    sa.Column('porteur_ids', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('ppg_id'),
                    schema='raw_data'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_ppg', schema='raw_data')
    op.drop_table('metadata_axe', schema='raw_data')
    # ### end Alembic commands ###
