"""ajout du porteur directeur dans la table metadata_porteur

Revision ID: 35c8bfc9c651
Revises: 16f4474e9466
Create Date: 2023-01-09 15:31:06.952105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c8bfc9c651'
down_revision = '16f4474e9466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_porteur', sa.Column('porteur_directeur', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_porteur', 'porteur_directeur', schema='raw_data')
    # ### end Alembic commands ###
