"""ajout_variable_ch_dp_table_metadata_chantier

Revision ID: 16f4474e9466
Revises: 1a049e97d770
Create Date: 2023-01-06 11:14:00.462031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f4474e9466'
down_revision = '1a049e97d770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_chantier', sa.Column('ch_dp', sa.VARCHAR(length=255), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_chantier', 'ch_dp', schema='raw_data')
    # ### end Alembic commands ###
