export interface VARIABLE_CONTENU_DISPONIBLE {
  'NEXT_BD_FF_BANDEAU_INDISPONIBILITE': boolean
  'NEXT_BD_FF_BANDEAU_INDISPONIBILITE_TEXTE': string
  'NEXT_BD_FF_BANDEAU_INDISPONIBILITE_TYPE': string
}
