export interface VARIABLE_CONTENU_DISPONIBLE {
  NEXT_BD_FF_BANDEAU_INDISPONIBILITE: boolean;
  NEXT_BD_FF_BANDEAU_INDISPONIBILITE_TEXTE: string;
  NEXT_BD_FF_BANDEAU_INDISPONIBILITE_TYPE: string;
  NEXT_PUBLIC_FF_NOUVELLE_PAGE_ACCUEIL: boolean;
  NEXT_PUBLIC_FF_RAPPORT_DETAILLE: boolean;
  NEXT_PUBLIC_FF_INFOBULLE_PONDERATION: boolean;
  NEXT_PUBLIC_FF_DATE_METEO: boolean;
  NEXT_PUBLIC_FF_ALERTES: boolean;
  NEXT_PUBLIC_FF_ALERTES_BAISSE: boolean;
  NEXT_PUBLIC_FF_APPLICATION_INDISPONIBLE: boolean;
  NEXT_PUBLIC_FF_FICHE_CONDUCTEUR: boolean;
  NEXT_PUBLIC_FF_GESTION_TOKEN_API: boolean;
  NEXT_PUBLIC_FF_TA_ANNUEL: boolean;
  NEXT_PUBLIC_FF_SUIVI_COMPLETUDE: boolean;
  NEXT_PUBLIC_FF_ALERTE_MAJ_INDICATEUR: boolean;
  NEXT_PUBLIC_FF_DOCS_API: boolean;
  NEXT_PUBLIC_FF_PPG_ARCHIVE: boolean;
  NEXT_PUBLIC_FF_POSER_UNE_QUESTION_INDICATEUR: boolean;
  NEXT_PUBLIC_FF_VIDEO_ACCUEIL: boolean;
  NEXT_PUBLIC_FF_PANEL_ADMIN: boolean;
  NEXT_PUBLIC_FF_MON_PROFIL: boolean;
  NEXT_PUBLIC_FF_ASK_AI: boolean;
  NEXT_PUBLIC_FF_CENTRE_AIDE_CUSTOM_PILOTE: boolean;
  NEXT_PUBLIC_FF_PILOTE_EVAL: boolean;
  NEXT_PUBLIC_FF_RAPPORT_COORDINATEURS: boolean;
  NEXT_PUBLIC_FF_RAPPORT_PVA: boolean;
  NEXT_PUBLIC_FF_CREATION_COMPTE_ARS: boolean;
  NEXT_PUBLIC_FF_MASQUER_INDICATEURS_NON_APPLICABLES: boolean;
  NEXT_PUBLIC_FF_ACCES_PILOTE: boolean;
  NEXT_PUBLIC_FF_COMPARAISON_TERRITOIRES: boolean;
  NEXT_PUBLIC_FF_FICHE_TERRITORIALE: boolean;
  NEXT_PUBLIC_FF_PROPOSITION_VOIR_HISTORIQUE: boolean;
  NEXT_PUBLIC_FF_PVA_VALEUR_DIFFERENTE: boolean;
  NEXT_PUBLIC_FF_LIEN_CONTACT_BREVO: boolean;
}

export const FEATURE_FLIP_KEYS = [
  "NEXT_PUBLIC_FF_NOUVELLE_PAGE_ACCUEIL",
  "NEXT_PUBLIC_FF_RAPPORT_DETAILLE",
  "NEXT_PUBLIC_FF_INFOBULLE_PONDERATION",
  "NEXT_PUBLIC_FF_DATE_METEO",
  "NEXT_PUBLIC_FF_ALERTES",
  "NEXT_PUBLIC_FF_ALERTES_BAISSE",
  "NEXT_PUBLIC_FF_APPLICATION_INDISPONIBLE",
  "NEXT_PUBLIC_FF_FICHE_CONDUCTEUR",
  "NEXT_PUBLIC_FF_GESTION_TOKEN_API",
  "NEXT_PUBLIC_FF_TA_ANNUEL",
  "NEXT_PUBLIC_FF_SUIVI_COMPLETUDE",
  "NEXT_PUBLIC_FF_ALERTE_MAJ_INDICATEUR",
  "NEXT_PUBLIC_FF_DOCS_API",
  "NEXT_PUBLIC_FF_PPG_ARCHIVE",
  "NEXT_PUBLIC_FF_POSER_UNE_QUESTION_INDICATEUR",
  "NEXT_PUBLIC_FF_VIDEO_ACCUEIL",
  "NEXT_PUBLIC_FF_PANEL_ADMIN",
  "NEXT_PUBLIC_FF_MON_PROFIL",
  "NEXT_PUBLIC_FF_ASK_AI",
  "NEXT_PUBLIC_FF_CENTRE_AIDE_CUSTOM_PILOTE",
  "NEXT_PUBLIC_FF_PILOTE_EVAL",
  "NEXT_PUBLIC_FF_RAPPORT_COORDINATEURS",
  "NEXT_PUBLIC_FF_RAPPORT_PVA",
  "NEXT_PUBLIC_FF_CREATION_COMPTE_ARS",
  "NEXT_PUBLIC_FF_MASQUER_INDICATEURS_NON_APPLICABLES",
  "NEXT_PUBLIC_FF_ACCES_PILOTE",
  "NEXT_PUBLIC_FF_COMPARAISON_TERRITOIRES",
  "NEXT_PUBLIC_FF_FICHE_TERRITORIALE",
  "NEXT_PUBLIC_FF_PROPOSITION_VOIR_HISTORIQUE",
  "NEXT_PUBLIC_FF_PVA_VALEUR_DIFFERENTE",
  "NEXT_PUBLIC_FF_LIEN_CONTACT_BREVO",
] as const;

export type FeatureFlipKey = (typeof FEATURE_FLIP_KEYS)[number];

export type FeatureFlipMap = Record<FeatureFlipKey, boolean>;

/** Labels lisibles pour l'interface d'administration */
export const FEATURE_FLIP_LABELS: Record<FeatureFlipKey, string> = {
  NEXT_PUBLIC_FF_NOUVELLE_PAGE_ACCUEIL: "Nouvelle page d'accueil",
  NEXT_PUBLIC_FF_RAPPORT_DETAILLE: "Rapport detaille",
  NEXT_PUBLIC_FF_INFOBULLE_PONDERATION: "Infobulle ponderation",
  NEXT_PUBLIC_FF_DATE_METEO: "Date meteo",
  NEXT_PUBLIC_FF_ALERTES: "Alertes",
  NEXT_PUBLIC_FF_ALERTES_BAISSE: "Alertes baisse",
  NEXT_PUBLIC_FF_APPLICATION_INDISPONIBLE: "Application indisponible",
  NEXT_PUBLIC_FF_FICHE_CONDUCTEUR: "Fiche conducteur",
  NEXT_PUBLIC_FF_GESTION_TOKEN_API: "Gestion token API",
  NEXT_PUBLIC_FF_TA_ANNUEL: "TA annuel",
  NEXT_PUBLIC_FF_SUIVI_COMPLETUDE: "Suivi completude",
  NEXT_PUBLIC_FF_ALERTE_MAJ_INDICATEUR: "Alerte MAJ indicateur",
  NEXT_PUBLIC_FF_DOCS_API: "Documentation API",
  NEXT_PUBLIC_FF_PPG_ARCHIVE: "PPG archive",
  NEXT_PUBLIC_FF_POSER_UNE_QUESTION_INDICATEUR: "Poser une question indicateur",
  NEXT_PUBLIC_FF_VIDEO_ACCUEIL: "Video accueil",
  NEXT_PUBLIC_FF_PANEL_ADMIN: "Panel administrateur",
  NEXT_PUBLIC_FF_MON_PROFIL: "Mon profil",
  NEXT_PUBLIC_FF_ASK_AI: "Ask AI",
  NEXT_PUBLIC_FF_CENTRE_AIDE_CUSTOM_PILOTE: "Centre d'aide custom Pilote",
  NEXT_PUBLIC_FF_PILOTE_EVAL: "Pilote Eval",
  NEXT_PUBLIC_FF_RAPPORT_COORDINATEURS: "Rapport coordinateurs",
  NEXT_PUBLIC_FF_RAPPORT_PVA: "Rapport PVA",
  NEXT_PUBLIC_FF_CREATION_COMPTE_ARS: "Creation compte ARS",
  NEXT_PUBLIC_FF_MASQUER_INDICATEURS_NON_APPLICABLES:
    "Masquer indicateurs non applicables",
  NEXT_PUBLIC_FF_ACCES_PILOTE: "Acces Pilote",
  NEXT_PUBLIC_FF_COMPARAISON_TERRITOIRES: "Comparaison territoires",
  NEXT_PUBLIC_FF_FICHE_TERRITORIALE: "Fiche territoriale",
  NEXT_PUBLIC_FF_PROPOSITION_VOIR_HISTORIQUE:
    "Voir historique des propositions",
  NEXT_PUBLIC_FF_PVA_VALEUR_DIFFERENTE: "PVA valeur differente",
  NEXT_PUBLIC_FF_LIEN_CONTACT_BREVO: "Lien contact Brevo",
};

export const VARIABLE_CONTENU_DISPONIBLE_ENV = [
  "NEXT_PUBLIC_FF_NOUVELLE_PAGE_ACCUEIL",
  "NEXT_PUBLIC_FF_RAPPORT_DETAILLE",
  "NEXT_PUBLIC_FF_INFOBULLE_PONDERATION",
  "NEXT_PUBLIC_FF_DATE_METEO",
  "NEXT_PUBLIC_LIMITE_CARACTERES_PUBLICATION",
  "NEXT_PUBLIC_FF_ALERTES",
  "NEXT_PUBLIC_FF_ALERTES_BAISSE",
  "NEXT_PUBLIC_FF_APPLICATION_INDISPONIBLE",
  "NEXT_PUBLIC_FF_FICHE_CONDUCTEUR",
  "NEXT_PUBLIC_FF_GESTION_TOKEN_API",
  "NEXT_PUBLIC_FF_TA_ANNUEL",
  "NEXT_PUBLIC_FF_SUIVI_COMPLETUDE",
  "NEXT_PUBLIC_FF_ALERTE_MAJ_INDICATEUR",
  "NEXT_PUBLIC_SCHEMA_VALIDATA_URL",
  "NEXT_PUBLIC_FF_DOCS_API",
  "NEXT_PUBLIC_FF_PPG_ARCHIVE",
  "NEXT_PUBLIC_FF_POSER_UNE_QUESTION_INDICATEUR",
  "NEXT_PUBLIC_DATE_BASCULE_AFFICHAGE_VALEURS_ANNEE_PRECEDENTE",
  "NEXT_PUBLIC_FF_VIDEO_ACCUEIL",
  "NEXT_PUBLIC_FF_PANEL_ADMIN",
  "NEXT_PUBLIC_FF_MON_PROFIL",
  "NEXT_PUBLIC_FF_ASK_AI",
  "NEXT_PUBLIC_FF_CENTRE_AIDE_CUSTOM_PILOTE",
  "NEXT_PUBLIC_FF_PILOTE_EVAL",
  "NEXT_PUBLIC_FF_RAPPORT_COORDINATEURS",
  "NEXT_PUBLIC_FF_ACCES_PILOTE",
  "NEXT_PUBLIC_FF_COMPARAISON_TERRITOIRES",
  "NEXT_PUBLIC_FF_REPARTITION_METEOS_V2",
] as const;

export type VariableContenuDisponibleEnv = {
  NEXT_PUBLIC_FF_NOUVELLE_PAGE_ACCUEIL: boolean;
  NEXT_PUBLIC_FF_RAPPORT_DETAILLE: boolean;
  NEXT_PUBLIC_FF_INFOBULLE_PONDERATION: boolean;
  NEXT_PUBLIC_FF_DATE_METEO: boolean;
  NEXT_PUBLIC_LIMITE_CARACTERES_PUBLICATION: number;
  NEXT_PUBLIC_FF_ALERTES: boolean;
  NEXT_PUBLIC_FF_ALERTES_BAISSE: boolean;
  NEXT_PUBLIC_FF_APPLICATION_INDISPONIBLE: boolean;
  NEXT_PUBLIC_FF_FICHE_CONDUCTEUR: boolean;
  NEXT_PUBLIC_FF_GESTION_TOKEN_API: boolean;
  NEXT_PUBLIC_FF_TA_ANNUEL: boolean;
  NEXT_PUBLIC_FF_SUIVI_COMPLETUDE: boolean;
  NEXT_PUBLIC_FF_ALERTE_MAJ_INDICATEUR: boolean;
  NEXT_PUBLIC_SCHEMA_VALIDATA_URL: string;
  NEXT_PUBLIC_FF_DOCS_API: boolean;
  NEXT_PUBLIC_FF_PPG_ARCHIVE: boolean;
  NEXT_PUBLIC_FF_POSER_UNE_QUESTION_INDICATEUR: boolean;
  NEXT_PUBLIC_DATE_BASCULE_AFFICHAGE_VALEURS_ANNEE_PRECEDENTE: string;
  NEXT_PUBLIC_FF_VIDEO_ACCUEIL: boolean;
  NEXT_PUBLIC_FF_PANEL_ADMIN: boolean;
  NEXT_PUBLIC_FF_MON_PROFIL: boolean;
  NEXT_PUBLIC_FF_ASK_AI: boolean;
  NEXT_PUBLIC_FF_CENTRE_AIDE_CUSTOM_PILOTE: boolean;
  NEXT_PUBLIC_FF_PILOTE_EVAL: boolean;
  NEXT_PUBLIC_FF_RAPPORT_COORDINATEURS: boolean;
  NEXT_PUBLIC_FF_ACCES_PILOTE: boolean;
  NEXT_PUBLIC_FF_COMPARAISON_TERRITOIRES: boolean;
  NEXT_PUBLIC_FF_REPARTITION_METEOS_V2: boolean;
};
