version: 2

models:
  - name: indicateur_territoire_valeur_evenement_avec_ta
    description: >
      Table reliant les indicateur_territoire_valeur_evenement à leur Taux d'avancement annuels (TAA)
      et taux d'avancement global (TAG) pour chaque VA non issue d'aggrégation et pour les territoires
      pour lesquels l'indicateur est applicable lorsque leur calcul est possible.
    config:
        materialized: table
    columns:
      - name : id
        tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
      - name : ta_indic_id
        tests:
          - not_null
