echo "Connect to" $DATABASE_URL
echo "DROP DATABASE" $TEST_DB "..."
psql -d $DATABASE_URL -c "DROP DATABASE IF EXISTS $TEST_DB;"
echo "CREATE DATABASE" $TEST_DB "..."
psql -d $DATABASE_URL -c "CREATE DATABASE $TEST_DB;"
