FROM python:3.11

# [setup.root-dir]
WORKDIR /app/data_management

## [install.uv] (last version)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh


COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

RUN uv python install

ENTRYPOINT ["uv","run"]

CMD ["dbt", "deps"]
