FROM ghcr.io/astral-sh/uv:trixie-slim
# [setup.root-dir]
WORKDIR /app/data_management

# [install.postgres]
RUN apt-get update && apt-get install -y \
    postgresql \
 && rm -rf /var/lib/apt/lists/*

ENV UV_ENV_FILE="/app/data_management/.env"

COPY . /app/data_management/

RUN uv python install

ENTRYPOINT ["uv","run", "python"]

CMD ["scripts/__main__.py"]
