FROM python:3.11

# [setup.root-dir]
WORKDIR /app/data_management

# [install.postgres]
RUN apt-get update && apt-get install -y \
    postgresql \
 && rm -rf /var/lib/apt/lists/*

## [install.uv] (last version)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

RUN uv python install

WORKDIR /app/data_management

ENTRYPOINT ["uv","run", "/bin/bash"]

CMD ["scripts/run_datajobs.sh"]
