FROM ghcr.io/astral-sh/uv:trixie-slim

# Set working directory
WORKDIR /app/data_management

ENV UV_ENV_FILE="/app/data_management/.env"

COPY . /app/data_management/

ENV UV_ENV_FILE="/app/data_management/.env"

# Use uv run as default entrypoint for all commands
ENTRYPOINT ["uv", "run"]

CMD ["dbt", "deps"]
