FROM ghcr.io/astral-sh/uv:trixie-slim

# Set working directory
WORKDIR /app/data_management

# Install PostgreSQL dependencies
RUN apt-get update && apt-get install -y \
    postgresql \
 && rm -rf /var/lib/apt/lists/*

ENV UV_ENV_FILE="/app/data_management/.env"

COPY . /app/data_management/

# Use uv run as default entrypoint for all commands
ENTRYPOINT ["uv", "run"]
CMD ["python", "scripts/__main__.py"]
