export enum EvenementValeurEnum {
  VALEUR_CREEE = "VALEUR_CREEE",
  VALEUR_MODIFIEE = "VALEUR_MODIFIEE",
  VALEUR_HISTORISEE = "VALEUR_HISTORISEE",
  PROPOSITION_VALEUR_CREEE = "PROPOSITION_VALEUR_CREEE",
  PROPOSITION_VALEUR_MODIFIEE = "PROPOSITION_VALEUR_MODIFIEE",
  PROPOSITION_VALEUR_SUPPRIMEE = "PROPOSITION_VALEUR_SUPPRIMEE",
  PROPOSITION_VALEUR_REFUSEE = "PROPOSITION_VALEUR_REFUSEE",
  PROPOSITION_VALEUR_ACCUSEE_RECEPTION = "PROPOSITION_VALEUR_ACCUSEE_RECEPTION",
  PROPOSITION_VALEUR_ACCEPTEE = "PROPOSITION_VALEUR_ACCEPTEE",
  PROPOSITION_VALEUR_IGNOREE_VALEUR_MODIFIEE = "PROPOSITION_VALEUR_IGNOREE_VALEUR_MODIFIEE",
  PROPOSITION_VALEUR_IGNOREE_VALEUR_HISTORISEE = "PROPOSITION_VALEUR_IGNOREE_VALEUR_HISTORISEE",
  PROPOSITION_VALEUR_ACCEPTEE_AVEC_MODIFICATION = "PROPOSITION_VALEUR_ACCEPTEE_AVEC_MODIFICATION",
}

export const EVENEMENT_VALEUR_PROPOSITION_VALEUR_TERMINEE = [
  EvenementValeurEnum.PROPOSITION_VALEUR_SUPPRIMEE,
  EvenementValeurEnum.PROPOSITION_VALEUR_REFUSEE,
  EvenementValeurEnum.PROPOSITION_VALEUR_IGNOREE_VALEUR_MODIFIEE,
  EvenementValeurEnum.PROPOSITION_VALEUR_IGNOREE_VALEUR_HISTORISEE,
  EvenementValeurEnum.PROPOSITION_VALEUR_ACCEPTEE,
  EvenementValeurEnum.PROPOSITION_VALEUR_ACCEPTEE_AVEC_MODIFICATION,
];
