name: Tests and Linters

on:
  push:
    branches:
      - dev
  pull_request:

env:
  NODE_VERSION: 24.9.0

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.6-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7433:5432
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Initialize database
        run: pnpm test:database:init

      - name: Run test command
        run: pnpm test

  lint:
    name: Run linters for code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run lint command
        run: pnpm lint

  lint-sql:
    name: Run linters on dbt models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install SQLFluff
        run: "pip install sqlfluff~=4.1.0 sqlfluff-templater-dbt~=4.1.0 dbt-core~=1.10.20 dbt-duckdb~=1.9.0"
      - name: Install dbt deps
        working-directory: data_management
        run: "dbt deps"
      - name: Lint models
        working-directory: data_management
        env:
          DBT_TARGET: local
        run: "sqlfluff lint models/ -v"
