name: Tests and Linters

on:
  push:
    branches:
      - dev
  pull_request:

env:
  NODE_VERSION: 18.x

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install npm packages
        continue-on-error: true
        run: npm ci

  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.9
        env:
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run test command
        run: npm run test:ci

  lint:
    name: Run linters for code
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run lint command
        run: npm run lint

  commitLint:
    name: Run linter for commit messages
    needs: install
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "[SOURCE=PULL REQUEST] Run lint command"
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --verbose
