name: Tests and Linters

on:
  push:
    branches:
      - dev
  pull_request:

env:
  NODE_VERSION: 24.9.0

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install npm packages
        continue-on-error: true
        run: npm ci

  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.6-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7433:5432
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Initialize database
        run: npm run test:database:init

      - name: Run test command
        run: npm test

  lint:
    name: Run linters for code
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and packages
        uses: ./.github/actions/setupNodeAndPackages
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run lint command
        run: npm run lint
